/* INVICTO OPS v18 · metas y KPIs reales */
function monthStartV18(d=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit'}).formatToParts(d);const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-01`}
function daysInMonthV18(ymd){const [y,m]=ymd.split('-').map(Number);return new Date(Date.UTC(y,m,0)).getUTCDate()}
function workingDaysV18(monthStart,throughDay=null){const [y,m]=monthStart.split('-').map(Number),end=throughDay||daysInMonthV18(monthStart);let n=0;for(let d=1;d<=end;d++){const wd=new Date(Date.UTC(y,m-1,d)).getUTCDay();if(wd!==0)n++}return n}
function currentBogotaPartsV18(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return Object.fromEntries(p.map(x=>[x.type,x.value]))}
function salesMonthV18(){const ms=monthStartV18();return state.sales.filter(s=>String(s.commercialDate||'').slice(0,7)===ms.slice(0,7))}
function currentTargetV18(){const ms=monthStartV18();return (state.monthlyTargets||[]).find(x=>String(x.month_start)===ms)||null}
function validSaleV18(s){return s.status!=='Duplicado'&&s.status!=='Perdido – datos inválidos'}
function managedSaleV18(s){return !['Nueva'].includes(s.status)}
function sellersV18(){return (state.profiles||[]).filter(p=>p.active&&p.role==='vendedor')}
function attemptMinutesV18(s){const arr=(opsAttemptsV13||[]).filter(a=>a.sale_id===s.dbId).sort((a,b)=>new Date(a.occurred_at)-new Date(b.occurred_at));if(!arr.length)return null;return Math.max(0,(new Date(arr[0].occurred_at)-new Date(s.receivedAt||s.createdAt))/60000)}
function fmtMinutesV18(v){if(v==null||!Number.isFinite(v))return '—';if(v<60)return `${Math.round(v)} min`;return `${(v/60).toFixed(1)} h`}

function goalStatsV18(){
  const ms=monthStartV18(),arr=salesMonthV18(),confirmed=arr.filter(s=>s.status==='Confirmada').length,target=Number(currentTargetV18()?.target_confirmed_sales||0),p=currentBogotaPartsV18(),day=Number(p.day),elapsed=workingDaysV18(ms,day),totalDays=workingDaysV18(ms),remainingDays=Math.max(1,totalDays-elapsed+1),remaining=Math.max(0,target-confirmed),required=target?Math.ceil(remaining/remainingDays):0,projection=elapsed?Math.round(confirmed/elapsed*totalDays):0,pct=target?Math.min(999,Math.round(confirmed/target*100)):0;
  return {ms,arr,confirmed,target,elapsed,totalDays,remainingDays,remaining,required,projection,pct};
}

async function setMonthlyTargetV18(){
  if(!isAdmin())return toast('Solo administración puede cambiar la meta');
  const g=goalStatsV18(),raw=prompt('Meta de ventas confirmadas para este mes',String(g.target||1500));if(!raw)return;const target=Math.floor(Number(raw));if(!target||target<=0)return toast('La meta debe ser mayor a 0');
  try{const {error}=await invictoSupabaseV12.rpc('save_monthly_target',{p_month_start:g.ms,p_target:target});if(error)throw error;await hydrateOpsV13(true);renderReports();if(typeof renderHome==='function'&&document.getElementById('view-home')?.classList.contains('active'))renderHome();toast(`Meta mensual actualizada: ${target}`)}catch(e){console.error(e);toast('No se pudo guardar la meta: '+(e.message||e))}
}

function goalPanelV18(){const g=goalStatsV18();if(!g.target)return `<div class="panel" style="margin-bottom:14px"><div class="panel-head"><div><h3>Meta mensual</h3><div class="muted">Todavía no hay una meta configurada para ${g.ms.slice(0,7)}.</div></div><div class="spacer"></div>${isAdmin()?'<button class="btn cyan sm" onclick="setMonthlyTargetV18()">Configurar meta</button>':''}</div></div>`;return `<div class="panel" style="margin-bottom:14px"><div class="panel-head"><div><h3>Meta mensual · ${g.target.toLocaleString('es-CO')} confirmadas</h3><div class="muted">${g.confirmed.toLocaleString('es-CO')} confirmadas · ${g.pct}% de cumplimiento</div></div><div class="spacer"></div>${isAdmin()?'<button class="btn light sm" onclick="setMonthlyTargetV18()">Editar meta</button>':''}</div><div class="panel-body"><div style="height:12px;background:#e8edf3;border-radius:99px;overflow:hidden"><div style="height:100%;width:${Math.min(100,g.pct)}%;background:#00cfa8"></div></div><div class="mini-grid" style="margin-top:14px"><div class="mini"><small>Faltan</small><b>${g.remaining}</b><div class="muted">confirmadas</div></div><div class="mini"><small>Necesarias / día</small><b>${g.required}</b><div class="muted">días hábiles Lun–Sáb</div></div><div class="mini"><small>Proyección</small><b>${g.projection}</b><div class="muted">al cierre del mes</div></div><div class="mini"><small>Días operativos</small><b>${g.elapsed}/${g.totalDays}</b><div class="muted">transcurridos</div></div></div></div></div>`}

window.renderReports=function(){
  const today=todaySales(),month=salesMonthV18(),confirmedToday=today.filter(s=>s.status==='Confirmada'),confirmedMonth=month.filter(s=>s.status==='Confirmada'),drafts=today.filter(s=>s.isDraft),valid=today.filter(validSaleV18),rate=valid.length?Math.round(confirmedToday.length/valid.length*100):0,createdValue=today.reduce((a,s)=>a+Number(s.price||0),0),confirmedValue=confirmedToday.reduce((a,s)=>a+Number(s.price||0),0);
  const source=groupCount(today,'source'),wh=groupCount(confirmedToday,'warehouse');
  el('view-reports').innerHTML=`<div class="page-title"><div><h1>Dashboard en vivo</h1><p>Ventas, borradores, confirmación, inventario y operación se calculan desde Supabase.</p></div><span class="tag green">EN VIVO</span></div>${goalPanelV18()}<div class="cards">${kpi('Ventas hoy',today.length,'incluye borradores')}${kpi('Borradores',drafts.length,'ventas activas')}${kpi('Confirmadas hoy',confirmedToday.length,'equipo')}${kpi('Tasa confirmación',rate+'%','válidas del día')}${kpi('Facturación creada',money(createdValue),'bruta')}${kpi('Facturación confirmada',money(confirmedValue),'confirmada')}</div><div class="grid-equal" style="margin-top:14px"><div class="panel"><div class="panel-head"><h3>Origen de ventas</h3></div><div class="panel-body">${objectStatLines(source)}</div></div><div class="panel"><div class="panel-head"><h3>Confirmadas por bodega</h3></div><div class="panel-body">${objectStatLines(wh)}</div></div></div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Resumen mensual</h3></div><div class="panel-body"><div class="statline"><span>Ventas creadas</span><b>${month.length}</b></div><div class="statline"><span>Confirmadas</span><b>${confirmedMonth.length}</b></div><div class="statline"><span>Borradores activos/registrados</span><b>${month.filter(s=>s.isDraft).length}</b></div><div class="statline"><span>Garantías abiertas</span><b>${state.guarantees.filter(g=>g.status!=='Cerrada').length}</b></div><div class="statline"><span>Novedades abiertas</span><b>${state.novelties.filter(n=>n.status!=='Cerrada').length}</b></div></div></div>`;
};

window.renderTeam=function(){
  const sellers=sellersV18(),today=todaySales(),metrics=sellers.map(p=>{const arr=today.filter(s=>s.advisorId===p.id),valid=arr.filter(validSaleV18),confirmed=valid.filter(s=>s.status==='Confirmada'),managed=valid.filter(managedSaleV18),mins=arr.map(attemptMinutesV18).filter(x=>x!=null),avg=mins.length?mins.reduce((a,b)=>a+b,0)/mins.length:null;return {p,assigned:arr.length,managed:managed.length,confirmed:confirmed.length,rate:valid.length?Math.round(confirmed.length/valid.length*100):0,avg,guar:state.guarantees.filter(g=>g.advisor===p.full_name&&g.status!=='Cerrada').length,nov:state.novelties.filter(n=>n.advisor===p.full_name&&n.status!=='Cerrada').length}});
  const totalConfirmed=today.filter(s=>s.status==='Confirmada').length,valid=today.filter(validSaleV18),globalRate=valid.length?Math.round(totalConfirmed/valid.length*100):0;
  el('view-team').innerHTML=`<div class="page-title"><div><h1>Equipo / KPIs</h1><p>El equipo ve el resultado global. Las métricas individuales quedan restringidas a administración y gerencia.</p></div></div><div class="cards">${kpi('Asesores activos',sellers.length,'reciben ventas')}${kpi('Ventas hoy',today.length,'equipo')}${kpi('Confirmadas',totalConfirmed,'hoy')}${kpi('Tasa global',globalRate+'%','válidas')}${kpi('Pendientes',today.filter(s=>['Nueva','No contesta','Seguimiento futuro','Pendiente stock'].includes(s.status)).length,'por gestionar')}${kpi('Alertas rojas',(state.alerts||[]).filter(a=>a.status==='open'&&a.severity==='roja').length,'operación')}</div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Participación global</h3></div><div class="panel-body"><div class="mini-grid">${metrics.map(m=>`<div class="mini"><small>${esc(m.p.full_name)}</small><b>${m.assigned}</b><div class="muted">ventas asignadas hoy</div></div>`).join('')||'<div class="muted">Sin asesores activos.</div>'}</div></div></div>${isAdmin()?`<div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Métricas individuales</h3><div class="spacer"></div><span class="tag dark">PRIVADO</span></div><div class="table-wrap"><table class="kpi-table"><thead><tr><th>Asesor</th><th>Asignadas</th><th>Gestionadas</th><th>Confirmadas</th><th>Tasa</th><th>1er contacto</th><th>Garantías</th><th>Novedades</th></tr></thead><tbody>${metrics.map(m=>`<tr><td><b>${esc(m.p.full_name)}</b></td><td>${m.assigned}</td><td>${m.managed}</td><td>${m.confirmed}</td><td><b>${m.rate}%</b></td><td>${fmtMinutesV18(m.avg)}</td><td>${m.guar}</td><td>${m.nov}</td></tr>`).join('')}</tbody></table></div></div>`:''}`;
};

const renderHomeBaseV18=window.renderHome;
window.renderHome=function(){renderHomeBaseV18();const h=document.getElementById('view-home');if(h)h.insertAdjacentHTML('afterbegin',goalPanelV18())};
