function nextFollowupDefaultV21(){let d=new Date();for(let i=0;i<8;i++){d=new Date(d.getTime()+86400000);const ymd=bogotaDateTextV21(d),dow=new Date(ymd+'T12:00:00Z').getUTCDay();if(dow!==0)return ymd+'T09:00'}return bogotaDateTextV21(new Date(Date.now()+86400000))+'T09:00'}
window.closeFollowupV21=function(){document.getElementById('followupV21')?.remove()};
window.scheduleRecoveryV21=function(id){const s=state.sales.find(x=>x.id===id);if(!s?.dbId)return toast('Pedido no encontrado');const w=document.createElement('div');w.id='followupV21';w.innerHTML=`<div class="modal-back-v21" onclick="closeFollowupV21()"></div><div class="modal-v21"><div class="modal-head-v21"><div><div class="eyebrow">SEGUIMIENTO</div><h3>${esc(s.id)} · ${esc(s.name)}</h3></div><button class="close" onclick="closeFollowupV21()">×</button></div><div class="modal-body-v21"><div class="field"><label>Fecha y hora en Colombia</label><input id="followupAtV21" type="datetime-local" value="${nextFollowupDefaultV21()}"></div><div class="field"><label>Motivo</label><select id="followupReasonV21"><option>Llamar más tarde</option><option>Espera salario / dinero</option><option>Cliente pidió otra fecha</option><option>Validar stock</option><option>Otro seguimiento</option></select></div></div><div class="modal-foot-v21"><button class="btn light" onclick="closeFollowupV21()">Cancelar</button><button class="btn cyan" onclick="saveFollowupV21('${esc(id)}')">Programar</button></div></div>`;document.body.appendChild(w)};
window.scheduleRecoveryV16=window.scheduleRecoveryV21;
window.saveFollowupV21=async function(id){const s=state.sales.find(x=>x.id===id);if(!s?.dbId)return;const raw=document.getElementById('followupAtV21')?.value,reason=document.getElementById('followupReasonV21')?.value||'Seguimiento';if(!raw)return toast('Selecciona fecha y hora');const d=new Date(raw+':00-05:00');if(Number.isNaN(d.getTime())||d<=new Date())return toast('Selecciona una fecha futura');try{const {error}=await invictoSupabaseV12.rpc('schedule_ops_followup',{p_sale_id:s.dbId,p_followup_at:d.toISOString(),p_reason:reason});if(error)throw error;closeFollowupV21();await hydrateOpsV13(true);switchView('recovery');toast('Seguimiento programado')}catch(e){toast('No se programó: '+(e.message||e))}};
window.renderRecovery=function(){const rows=advisorSales().filter(s=>['No contesta','Seguimiento futuro','Pendiente stock'].includes(s.status)).sort((a,b)=>saleUrgencyV21(b)-saleUrgencyV21(a)),overdue=rows.filter(s=>s.nextFollowupAt&&new Date(s.nextFollowupAt)<=new Date()).length,stock=rows.filter(s=>s.status==='Pendiente stock').length;el('view-recovery').innerHTML=`<div class="page-title"><div><h1>Recuperación</h1><p>Priorizada por vencimiento. Los relojes solo corren Lun–Sáb 08:00–18:00.</p></div></div><div class="cards recovery-cards-v21">${kpi('Pendientes',rows.length,'por recuperar')}${kpi('Vencidas',overdue,'actuar ahora')}${kpi('Esperando stock',stock,'seguimiento de disponibilidad')}</div><div class="panel" style="margin-top:14px"><div class="table-wrap"><table><thead><tr><th>Prioridad</th><th>Cliente</th><th>Teléfono</th><th>Estado</th><th>Intentos</th><th>Asesor</th><th>Próxima acción</th><th>Acciones</th></tr></thead><tbody>${rows.map(s=>`<tr class="${saleUrgencyV21(s)>=60000?'row-red-v21':''}"><td>${s.status==='Pendiente stock'?'<span class="tag amber">STOCK</span>':s.nextFollowupAt&&new Date(s.nextFollowupAt)<=new Date()?'<span class="tag red">VENCIDA</span>':'<span class="tag blue">PROGRAMADA</span>'}</td><td><b>${esc(s.name)}</b><div class="muted">${esc(s.city)}</div></td><td>${esc(s.phone)}</td><td>${statusTag(s.status)}</td><td>${Number(s.recoveryStage??s.attempts??0)}/3</td><td>${esc(s.advisor)}</td><td><b>${esc(followupLabelV16(s))}</b></td><td><div class="row-actions-v21"><button class="btn light sm" onclick="openOrder('${esc(s.id)}')">Abrir</button>${s.phone?`<button class="btn light sm" onclick="openWhatsAppV21('${esc(s.phone)}')">WhatsApp</button>`:''}${s.status!=='Pendiente stock'&&Number(s.recoveryStage||0)<3?`<button class="btn navy sm" onclick="registerNoAnswerV16('${esc(s.id)}')">No contestó</button>`:''}<button class="btn light sm" onclick="scheduleRecoveryV21('${esc(s.id)}')">Programar</button>${Number(s.recoveryStage||0)>=3?`<button class="btn danger-lite sm" onclick="closeNoContactV16('${esc(s.id)}')">Cerrar sin contacto</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="8" class="muted">Sin recuperaciones pendientes.</td></tr>'}</tbody></table></div></div>`};

function topUrgentSalesV21(){return todaySales().filter(s=>ACTIVE_SALES_V21.includes(s.status)).sort((a,b)=>saleUrgencyV21(b)-saleUrgencyV21(a)).slice(0,5)}
const renderHomeBaseV21=window.renderHome;
window.renderHome=function(){renderHomeBaseV21();const h=el('view-home');if(!h)return;const rows=topUrgentSalesV21(),red=(state.alerts||[]).filter(a=>a.status==='open'&&a.severity==='roja').length,due=todaySales().filter(s=>s.nextFollowupAt&&new Date(s.nextFollowupAt)<=new Date()).length;const html=`<div class="ops-now-v21"><div class="ops-now-head-v21"><div><div class="eyebrow">ATENCIÓN AHORA</div><h3>Cola priorizada automáticamente</h3></div><div class="ops-now-stats-v21"><span><b>${red}</b> alertas rojas</span><span><b>${due}</b> seguimientos vencidos</span></div></div><div class="ops-now-list-v21">${rows.map(s=>`<button onclick="switchView('sales');openOrderV20('${esc(s.id)}')"><span>${slaTagV21(s)}</span><b>${esc(s.id)} · ${esc(s.name)}</b><small>${esc(s.status)} · ${fmtBusinessAgeV21(s)}</small></button>`).join('')||'<div class="muted">No hay ventas urgentes en este momento.</div>'}</div></div>`;const hero=h.querySelector('.hero');if(hero)hero.insertAdjacentHTML('afterend',html);else h.insertAdjacentHTML('afterbegin',html)};

const renderAIBaseV21=window.renderAI;
window.renderAI=function(){renderAIBaseV21();const actions=document.querySelector('.ai-actions-v20');if(!actions||actions.querySelector('.context-ai-v21'))return;let prompt='Analiza la pantalla actual y dime las 3 acciones más importantes.';if(currentView==='sales')prompt='Analiza las ventas de hoy y prioriza qué debo gestionar primero.';if(currentView==='inventory')prompt='Analiza el inventario y señala riesgos reales de stock y despacho.';if(currentView==='recovery')prompt='Analiza recuperación y seguimientos vencidos y dime por dónde empezar.';if(currentView==='cuts')prompt='Analiza qué está listo o bloqueado para corte y despacho.';if(editingSaleId&&el('orderDrawer')?.classList.contains('open'))prompt=`Analiza el pedido ${editingSaleId} y dime la siguiente acción.`;actions.insertAdjacentHTML('afterbegin',`<button class="ai-action-v20 context-ai-v21" onclick='aiAskQuickV19(${JSON.stringify(prompt)})'>Analizar lo que estoy viendo<small>La I.A. toma el contexto de esta pantalla.</small></button>`)};

const renderConfigBaseV21=window.renderConfig;
window.renderConfig=async function(){await renderConfigBaseV21();if(!isAdmin())return;try{const {data,error}=await invictoSupabaseV12.rpc('ops_system_health');if(error)throw error;const h=data||{},host=el('view-config');host?.insertAdjacentHTML('beforeend',`<div class="panel health-v21" style="margin-top:14px"><div class="panel-head"><div><h3>Salud del sistema</h3><div class="muted">Diagnóstico automático de operación e integraciones.</div></div><div class="spacer"></div><span class="tag ${Number(h.webhook_errors_24h||0)?'red':'green'}">${Number(h.webhook_errors_24h||0)?`${h.webhook_errors_24h} error webhook`:'SIN ERRORES CRÍTICOS'}</span></div><div class="health-grid-v21"><div><small>Último webhook</small><b>${h.last_webhook_at?fmtDate(h.last_webhook_at):'—'}</b></div><div><small>Ventas hoy</small><b>${Number(h.sales_today||0)}</b></div><div><small>Referencias pendientes</small><b>${Number(h.pending_mapping||0)}</b></div><div><small>Sin asignar</small><b>${Number(h.unassigned_today||0)}</b></div><div><small>Alertas rojas</small><b>${Number(h.red_alerts||0)}</b></div><div><small>Códigos LogiGho</small><b>${Number(h.logigho_city_codes||0)}</b></div></div>${Array.isArray(h.inventory)?`<div class="health-inventory-v21">${h.inventory.map(x=>`<div><b>${esc(x.warehouse)}</b><span>${Number(x.physical||0).toLocaleString('es-CO')} físico · ${Number(x.variants||0)} variantes</span><small>Última carga: ${x.last_import_at?fmtDate(x.last_import_at):'sin registro'}${x.last_import_file?` · ${esc(x.last_import_file)}`:''}</small></div>`).join('')}</div>`:''}</div>`)}catch(e){console.warn('Health v21',e)}};

installSmartFallbackV21();
