function renderMonthlyTableV23(){
  const body=el('monthlySalesBodyV23'),count=el('monthlyCountV23'),pager=el('monthlyPagerV23');if(!body)return;
  const rows=filteredMonthlyRowsV23(),pages=Math.max(1,Math.ceil(rows.length/monthlyPageSizeV23));monthlyPageV23=Math.min(monthlyPageV23,pages);const from=(monthlyPageV23-1)*monthlyPageSizeV23,part=rows.slice(from,from+monthlyPageSizeV23);
  if(count)count.textContent=`${rows.length.toLocaleString('es-CO')} ventas visibles`;
  body.innerHTML=part.map(r=>{const code=rowCodeV23(r),dt=new Date(r.received_at||r.created_at),type=isDraftV23(r)?'<span class="tag amber">BORRADOR</span>':r.source==='Shopify'?'<span class="tag blue">PEDIDO</span>':'<span class="tag gray">MANUAL</span>';return `<tr><td><b>${esc(code)}</b><div class="muted">${esc(r.commercial_date||'')}</div></td><td>${Number.isNaN(dt.getTime())?'—':dt.toLocaleTimeString('es-CO',{timeZone:'America/Bogota',hour:'2-digit',minute:'2-digit'})}</td><td><b>${esc(r.customer_name||'Sin nombre')}</b><div class="muted mono">${esc(r.customer_phone||'')}</div></td><td>${esc(r.customer_city||'—')}<div class="muted">${esc(r.customer_department||'')}</div></td><td>${esc(r.advisor_name||'Sin asignar')}</td><td>${type}</td><td>${reportStatusTagV23(r)}</td><td><b>${Number(r.quantity||0)}</b><div class="muted">${Number(r.item_count||0)} líneas</div></td><td><b>${money(r.total_price)}</b></td><td>${r.mapping_status==='pending'?'<span class="tag amber">PENDIENTE</span>':'<span class="tag green">LISTO</span>'}<div class="muted">${Number(r.reserved_quantity||0)} reservadas</div></td><td>${esc(r.warehouse_name||'—')}<div class="muted">${esc(r.tracking_number||'')}</div></td><td><button class="btn light sm" onclick="openMonthlySaleV23('${r.id}')">Ver venta</button></td></tr>`}).join('')||'<tr><td colspan="12" class="muted">No hay ventas con esos filtros.</td></tr>';
  if(pager)pager.innerHTML=`<button class="btn light sm" ${monthlyPageV23<=1?'disabled':''} onclick="monthlyPageV23--;renderMonthlyTableV23()">← Anterior</button><span>Página <b>${monthlyPageV23}</b> de <b>${pages}</b></span><button class="btn light sm" ${monthlyPageV23>=pages?'disabled':''} onclick="monthlyPageV23++;renderMonthlyTableV23()">Siguiente →</button>`;
}
window.monthlyFilterV23=function(){monthlyPageV23=1;renderMonthlyTableV23()};
window.changeMonthV23=function(ym){if(!/^\d{4}-\d{2}$/.test(ym))return;monthlySelectedV23=`${ym}-01`;monthlyRowsV23=[];monthlyPrevRowsV23=[];loadMonthlyV23(true)};
window.shiftMonthV23=function(n){monthlySelectedV23=addMonthsV23(monthlySelectedV23||monthStartFromYmV23(bogotaMonthV23()),n);monthlyRowsV23=[];monthlyPrevRowsV23=[];loadMonthlyV23(true)};
window.currentMonthV23=function(){changeMonthV23(bogotaMonthV23())};
window.previousMonthV23=function(){changeMonthV23(addMonthsV23(monthStartFromYmV23(bogotaMonthV23()),-1).slice(0,7))};
window.refreshMonthlyV23=function(){monthlyRowsV23=[];monthlyPrevRowsV23=[];loadMonthlyV23(true)};
window.exportMonthlyV23=function(){
  const rows=filteredMonthlyRowsV23();if(!rows.length)return toast('No hay ventas para exportar');if(typeof XLSX==='undefined')return toast('No está disponible el exportador Excel');
  const data=rows.map(r=>({Fecha:r.commercial_date,Hora:new Date(r.received_at||r.created_at).toLocaleTimeString('es-CO',{timeZone:'America/Bogota',hour:'2-digit',minute:'2-digit'}),Pedido:rowCodeV23(r),Tipo:isDraftV23(r)?'Borrador':r.source_entity_type,Cliente:r.customer_name,Telefono:r.customer_phone,Email:r.customer_email,Ciudad:r.customer_city,Departamento:r.customer_department,Direccion:r.customer_address,Asesor:r.advisor_name,Estado:reportStatusLabelV23(r.status,r.loss_reason),Unidades:Number(r.quantity||0),Valor:Number(r.total_price||0),Origen:r.source,Mapeo:r.mapping_status,Bodega:r.warehouse_name,Transportadora:r.carrier,Guia:r.tracking_number,Estado_logistico:shipmentLabelV23(r.shipment_status),Intentos:Number(r.attempt_count||0),Confirmada:r.confirmed_at||''}));
  const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data);XLSX.utils.book_append_sheet(wb,ws,'Ventas');XLSX.writeFile(wb,`INVICTO_Ventas_${monthlySelectedV23.slice(0,7)}.xlsx`);
};

window.renderMonthlySalesV23=function(skipLoad=false){
  if(!monthlySelectedV23)monthlySelectedV23=monthStartFromYmV23(bogotaMonthV23());
  const host=el('view-monthly-sales');if(!host)return;
  if(!skipLoad&&(!monthlyRowsV23.length||!monthlyRowsV23[0]?.commercial_date?.startsWith(monthlySelectedV23.slice(0,7)))){loadMonthlyV23();return;}
  const cur=reportMetricsV23(monthlyRowsV23),prev=reportMetricsV23(monthlyPrevRowsV23),status=groupRowsV23(monthlyRowsV23,'status'),source=groupRowsV23(monthlyRowsV23,'source'),advisor=groupRowsV23(monthlyRowsV23,'advisor_name');
  host.innerHTML=`<div class="page-title month-title-v23"><div><div class="eyebrow">HISTORIAL COMERCIAL</div><h1>Ventas individuales · ${monthLabelV23(monthlySelectedV23)}</h1><p>Cada venta del mes, con cliente, asesor, estado, valor, surtido y despacho.</p></div><div class="month-title-actions"><button class="btn light sm" onclick="shiftMonthV23(-1)">←</button><input type="month" class="search" value="${monthlySelectedV23.slice(0,7)}" onchange="changeMonthV23(this.value)"><button class="btn light sm" onclick="shiftMonthV23(1)">→</button><button class="btn light sm" onclick="refreshMonthlyV23()">↻ Actualizar</button><button class="btn navy sm" onclick="exportMonthlyV23()">Exportar Excel</button></div></div>
  <div class="month-quick-v23"><button onclick="currentMonthV23()">Mes actual</button><button onclick="previousMonthV23()">Mes anterior</button><span>Comparando contra <b>${monthLabelV23(addMonthsV23(monthlySelectedV23,-1))}</b></span></div>
  ${monthlyCardsV23(cur,prev)}
  <div class="grid-2 month-grid-v23" style="margin-top:14px"><div class="panel"><div class="panel-head"><h3>Ventas por día</h3><div class="spacer"></div><span class="tag blue">${cur.sales} TOTAL</span></div><div class="panel-body">${miniBarsV23(monthlyRowsV23)}</div></div><div class="panel"><div class="panel-head"><h3>Estado del mes</h3></div><div class="panel-body">${statLinesV23(status,cur.sales)}</div></div></div>
  <div class="grid-equal" style="margin-top:14px"><div class="panel"><div class="panel-head"><h3>Origen</h3></div><div class="panel-body">${statLinesV23(source,cur.sales)}</div></div>${isAdmin()?`<div class="panel"><div class="panel-head"><h3>Ventas por asesor</h3><div class="spacer"></div><span class="tag dark">PRIVADO</span></div><div class="panel-body">${statLinesV23(advisor,cur.sales)}</div></div>`:`<div class="panel"><div class="panel-head"><h3>Indicadores</h3></div><div class="panel-body"><div class="statline"><span>Conversión</span><b>${cur.rate}%</b></div><div class="statline"><span>Perdidas</span><b>${cur.lost}</b></div><div class="statline"><span>Ticket promedio</span><b>${money(cur.aov)}</b></div></div></div>`}</div>
  <div class="panel" style="margin-top:14px"><div class="panel-head month-filter-head-v23"><div class="toolbar"><input id="monthSearchV23" class="search" placeholder="Pedido, cliente, teléfono, ciudad o guía…" oninput="monthlyFilterV23()"><select id="monthStatusV23" class="search" onchange="monthlyFilterV23()"><option value="">Todos los estados</option>${statusOptionsV23().map(x=>`<option value="${esc(x)}">${esc(reportStatusLabelV23(x))}</option>`).join('')}</select>${isAdmin()?`<select id="monthAdvisorV23" class="search" onchange="monthlyFilterV23()"><option value="">Todos los asesores</option>${advisorOptionsV23().map(x=>`<option>${esc(x)}</option>`).join('')}</select>`:''}<select id="monthTypeV23" class="search" onchange="monthlyFilterV23()"><option value="">Pedido + borrador + manual</option><option value="order">Pedidos</option><option value="draft_order">Borradores</option></select><select id="monthMappingV23" class="search" onchange="monthlyFilterV23()"><option value="">Todos los surtidos</option><option value="pending">Referencias pendientes</option><option value="mapped">Referencias listas</option></select></div><div class="spacer"></div><span id="monthlyCountV23" class="tag blue"></span></div>
  <div class="table-wrap"><table class="monthly-table-v23"><thead><tr><th>Pedido / fecha</th><th>Hora</th><th>Cliente</th><th>Ciudad</th><th>Asesor</th><th>Tipo</th><th>Estado</th><th>Uds.</th><th>Valor</th><th>Surtido</th><th>Bodega / guía</th><th></th></tr></thead><tbody id="monthlySalesBodyV23"></tbody></table></div><div id="monthlyPagerV23" class="monthly-pager-v23"></div></div>`;
  renderMonthlyTableV23();
};
