/* INVICTO OPS v46 · Novedades flexibles, con o sin venta enlazada */
(function(){
  let data46=[],loading46=false,search46='';
  const e=v=>typeof esc==='function'?esc(v??''):String(v??'');
  const admin=()=>typeof isAdmin==='function'&&isAdmin();
  function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim()}
  function cell(r,names){const ks=Object.keys(r),want=names.map(norm);const exact=ks.find(k=>want.includes(norm(k)));if(exact)return r[exact];const partial=ks.find(k=>want.some(w=>norm(k).includes(w)));return partial?r[partial]:''}
  function dateText(v){if(!v)return '';const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(m){let y=Number(m[3]);if(y<100)y+=2000;return `${y}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`;}return ''}
  function filtered(){const q=search46.trim().toLowerCase();return data46.filter(r=>!q||[r.order_ref,r.customer_name,r.phone,r.city,r.guide,r.advisor_name,r.description,r.status].some(x=>String(x||'').toLowerCase().includes(q)))}
  function tag(r){const m={abierta:['red','ABIERTA'],en_gestion:['amber','EN GESTIÓN'],esperando_externo:['blue','ESPERANDO EXTERNO'],pendiente_validacion_admin:['green','PENDIENTE VALIDACIÓN'],cerrada:['gray','CERRADA']},x=m[r.status]||['gray',r.status];return `<span class="tag ${x[0]}">${e(x[1])}</span>`}
  function paint(){const host=document.getElementById('view-novelties');if(!host)return;const rows=filtered();host.innerHTML=`<div class="page-title"><div><div class="eyebrow">LOGÍSTICA · NOVEDADES</div><h1>Novedades logísticas</h1><p>El archivo se guarda aunque una fila todavía no tenga venta asociada. Pedido, guía, teléfono y fecha se usan para intentar enlazarla.</p></div>${admin()?`<label class="btn cyan">Cargar Excel de novedades<input type="file" accept=".xlsx,.xls" hidden onchange="importNovelties(this.files[0])"></label>`:''}</div>
  <div class="panel"><div class="panel-head"><input class="search" style="min-width:300px" placeholder="Pedido, guía, cliente, teléfono, novedad…" value="${e(search46)}" oninput="noveltySearchV46(this.value)"><div class="spacer"></div><span class="tag blue">${rows.length} visibles</span><button class="btn light sm" onclick="loadNoveltiesV46(true)">↻ Actualizar</button></div>${loading46&&!data46.length?'<div class="panel-body">Cargando novedades…</div>':`<div class="table-wrap"><table><thead><tr><th>Pedido / vínculo</th><th>Cliente</th><th>Teléfono</th><th>Fecha</th><th>Guía</th><th>Asesor</th><th>Novedad</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${e(r.order_ref||'Sin pedido')}</b><div>${r.linked?'<span class="tag green">VENTA ENLAZADA</span>':'<span class="tag amber">SIN VENTA ENLAZADA</span>'}</div></td><td><b>${e(r.customer_name||'Sin nombre')}</b><div class="muted">${e(r.city||'')}</div></td><td>${e(r.phone||'—')}</td><td>${e(r.event_date||'—')}</td><td>${e(r.guide||'—')}</td><td>${e(r.advisor_name||'Sin asignar')}</td><td>${e(r.description||'')}</td><td>${tag(r)}</td><td>${r.status==='cerrada'?'<span class="muted">Cerrada</span>':`<button class="btn light sm" onclick="manageNoveltyV46('${r.id}')">Gestionar</button>`}</td></tr>`).join('')||'<tr><td colspan="9" class="muted">Sin novedades.</td></tr>'}</tbody></table></div>`}</div>`}
  async function load(force=false){if(loading46||typeof invictoSupabaseV12==='undefined')return;loading46=true;if(currentView==='novelties')paint();try{const {data,error}=await invictoSupabaseV12.rpc('get_novelties_v46');if(error)throw error;data46=data||[];}catch(err){console.error('novelties v46',err);toast('No se pudieron cargar Novedades: '+(err.message||err));}finally{loading46=false;if(currentView==='novelties')paint();}}
  window.loadNoveltiesV46=load;
  window.renderNovelties=function(){paint();load(false)};
  window.noveltySearchV46=v=>{search46=v;paint()};
  window.manageNoveltyV46=async function(id){const r=data46.find(x=>x.id===id);if(!r)return;const allowed=admin()?'abierta|en_gestion|esperando_externo|pendiente_validacion_admin|cerrada':'abierta|en_gestion|esperando_externo|pendiente_validacion_admin';const st=prompt(`Estado actual: ${r.status}\nOpciones: ${allowed}`,r.status);if(!st)return;const desc=prompt('Descripción / gestión',r.description||'')||r.description;try{const {error}=await invictoSupabaseV12.rpc('save_ops_novelty',{p_novelty_id:r.id,p_sale_id:r.sale_id||null,p_description:desc,p_status:st,p_source:r.source||'manual',p_phone:r.phone||null,p_date:r.event_date||null});if(error)throw error;await load(true);toast('Novedad actualizada');}catch(err){console.error(err);toast('No se actualizó: '+(err.message||err))}};
  window.importNovelties=async function(file){if(!file||!admin())return;try{if(typeof XLSX==='undefined')throw new Error('No está disponible el lector Excel');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});if(!rows.length)throw new Error('El archivo está vacío');const payload=rows.map(r=>({
      phone:String(cell(r,['TELEFONO','CELULAR','NUMERO DE TELEFONO','PHONE'])||'').trim(),
      date:dateText(cell(r,['FECHA','FECHA NOVEDAD','FECHA DE NOVEDAD','DATE'])),
      description:String(cell(r,['NOVEDAD','GESTION','DESCRIPCION','MOTIVO','OBSERVACION','ESTADO NOVEDAD'])||'Novedad importada').trim(),
      order:String(cell(r,['PEDIDO','ORDEN','ID PEDIDO','NUMERO DE PEDIDO','ORDER'])||'').trim(),
      guide:String(cell(r,['GUIA','NUMERO DE GUIA','NUMERO DE SEGUIMIENTO','TRACKING','TRACKING NUMBER'])||'').trim(),
      customer:String(cell(r,['CLIENTE','NOMBRE','NOMBRE DEL CLIENTE','DESTINATARIO'])||'').trim(),
      city:String(cell(r,['CIUDAD','MUNICIPIO','COMUNA PUEBLO'])||'').trim()
    })).filter(r=>r.phone||r.order||r.guide||r.description!=='Novedad importada');if(!payload.length)throw new Error('No encontré filas utilizables');toast(`Procesando ${payload.length} novedades…`);const {data,error}=await invictoSupabaseV12.rpc('import_ops_novelties_v46',{p_rows:payload,p_source_file:file.name});if(error)throw error;await load(true);toast(`${Number(data?.inserted||0)} novedades cargadas · ${Number(data?.matched||0)} enlazadas · ${Number(data?.unmatched||0)} sin venta`);}catch(err){console.error('novelty import v46',err);toast('No se pudo importar: '+(err.message||err));}};
  setTimeout(()=>load(true),1100);
})();
