function renderCuts(){
  const pending=state.sales.filter(s=>s.status==='Confirmada'&&!s.cutId);
  el('view-cuts').innerHTML=`<div class="page-title"><div><h1>Cortes / Guías</h1><p>Cortes fijos 11:00 y 17:00. Administración y gerencia pueden ejecutar un corte manual en cualquier momento.</p></div>${isAdmin()?'<button class="btn cyan" onclick="createCut()">Crear corte ahora</button>':''}</div><div class="cards">${WAREHOUSES.map(w=>kpi(w,pending.filter(s=>s.warehouse===w).length,'pedidos pendientes')).join('')}</div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Pedidos listos para próximo corte</h3><div class="spacer"></div><span class="tag blue">${pending.length} pedidos</span></div><div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Asesor</th><th>Bodega</th><th>Transportadora</th><th>Valor</th></tr></thead><tbody>${pending.map(s=>`<tr><td>${s.id}</td><td>${esc(s.name)}</td><td>${esc(s.advisor)}</td><td>${esc(s.warehouse)}</td><td>${esc(s.carrier||'Por definir')}</td><td>${money(s.price)}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">No hay pedidos pendientes.</td></tr>'}</tbody></table></div></div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Historial de cortes</h3></div><div class="table-wrap"><table><thead><tr><th>Corte</th><th>Fecha</th><th>Creado por</th><th>Pedidos</th><th>Hoko BOG</th><th>Hoko MED</th><th>LogiGho</th><th>BGA</th></tr></thead><tbody>${state.cuts.map(c=>`<tr><td>${c.id}</td><td>${fmtDate(c.createdAt)}</td><td>${esc(c.createdBy)}</td><td>${c.saleIds.length}</td>${WAREHOUSES.map(w=>`<td>${c.byWarehouse[w]||0}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="8" class="muted">Aún no hay cortes.</td></tr>'}</tbody></table></div></div>`;
}
function createCut(){if(!isAdmin())return;const pending=state.sales.filter(s=>s.status==='Confirmada'&&!s.cutId);if(!pending.length){toast('No hay pedidos para cortar');return;}const id='C-'+String(state.cuts.length+1).padStart(3,'0');const by={};pending.forEach(s=>{s.cutId=id;by[s.warehouse]=(by[s.warehouse]||0)+1;});state.cuts.unshift({id,createdAt:new Date().toISOString(),createdBy:session.name,saleIds:pending.map(s=>s.id),byWarehouse:by});saveState();renderCuts();toast(`Corte ${id} creado`);}

function renderGuarantees(){
  const rows=state.guarantees.filter(g=>!isAdvisor()||g.advisor===session.name);
  el('view-guarantees').innerHTML=`<div class="page-title"><div><h1>Garantías</h1><p>El asesor original gestiona. Recordatorio cada 24 horas. Cierre definitivo solo por administración.</p></div><button class="btn cyan" onclick="newGuarantee()">+ Abrir garantía</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Caso</th><th>Cliente</th><th>Asesor</th><th>Motivo</th><th>Dependencia</th><th>Estado</th><th>Última gestión</th><th>Acción</th></tr></thead><tbody>${rows.map(g=>`<tr><td><b>${g.id}</b><div class="muted">${g.saleId}</div></td><td>${esc(g.client)}</td><td>${esc(g.advisor)}</td><td>${esc(g.reason)}</td><td>${esc(g.external||'Interna')}</td><td>${statusTag(g.status)}</td><td>${fmtDate(g.lastUpdate)}</td><td><button class="btn light sm" onclick="manageGuarantee('${g.id}')">Gestionar</button></td></tr>`).join('')||'<tr><td colspan="8" class="muted">Sin garantías.</td></tr>'}</tbody></table></div></div>`;
}
function newGuarantee(){const sale=state.sales.find(s=>!isAdvisor()||s.advisor===session.name)||state.sales[0];if(!sale){toast('No hay venta para asociar');return;}const reason=prompt('Motivo: Calidad/defectuoso, talla equivocada, diseño equivocado o faltante','Calidad / defectuoso');if(!reason)return;state.guarantees.unshift({id:'G-'+String(state.guarantees.length+1).padStart(3,'0'),saleId:sale.id,advisor:sale.advisor,client:sale.name,reason,status:'Abierta',external:'',lastUpdate:new Date().toISOString(),proposedSolution:'',adminDecision:''});saveState();renderGuarantees();toast('Garantía abierta');}
function manageGuarantee(id){const g=state.guarantees.find(x=>x.id===id);if(!g)return;const options=isAdmin()?'Abierta|En gestión|Esperando respuesta externa|Resuelta pendiente de validación|Cerrada':'Abierta|En gestión|Esperando respuesta externa|Resuelta pendiente de validación';const st=prompt(`Estado actual: ${g.status}\nOpciones: ${options}`,g.status);if(!st)return;if(st==='Cerrada'&&!isAdmin()){toast('Solo administración puede cerrar');return;}g.status=st;g.lastUpdate=new Date().toISOString();saveState();renderGuarantees();toast('Garantía actualizada');}

function renderNovelties(){
  const rows=state.novelties.filter(n=>!isAdvisor()||n.advisor===session.name);
  el('view-novelties').innerHTML=`<div class="page-title"><div><h1>Novedades logísticas</h1><p>Gestión obligatoria el mismo día. Excel manual disponible como plan B si no hay API.</p></div>${isAdmin()?'<label class="btn cyan">Cargar Excel de novedades<input type="file" accept=".xlsx,.xls" hidden onchange="importNovelties(this.files[0])"></label>':''}</div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Caso</th><th>Cliente</th><th>Teléfono</th><th>Fecha</th><th>Guía</th><th>Asesor</th><th>Novedad</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${rows.map(n=>`<tr><td><b>${n.id}</b></td><td>${esc(n.client)}</td><td>${esc(n.phone)}</td><td>${esc(n.date||'')}</td><td>${esc(n.guide||'—')}</td><td>${esc(n.advisor)}</td><td>${esc(n.type)}</td><td>${statusTag(n.status)}</td><td><button class="btn light sm" onclick="manageNovelty('${n.id}')">Gestionar</button></td></tr>`).join('')||'<tr><td colspan="9" class="muted">Sin novedades.</td></tr>'}</tbody></table></div></div>`;
}
async function importNovelties(file){if(!file||!isAdmin())return;try{const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});let created=0;rows.forEach(r=>{const phone=extractPhone(r);if(!phone)return;const date=extractDate(r);const candidates=state.sales.filter(s=>digits(s.phone)===digits(phone));let sale=null;if(candidates.length===1)sale=candidates[0];else if(candidates.length>1)sale=candidates.sort((a,b)=>Math.abs(new Date(a.createdAt)-new Date(date||Date.now()))-Math.abs(new Date(b.createdAt)-new Date(date||Date.now())))[0];if(!sale)return;state.novelties.unshift({id:'N-'+String(state.novelties.length+1).padStart(3,'0'),saleId:sale.id,advisor:sale.advisor,client:sale.name,phone:sale.phone,date:date||new Date().toISOString().slice(0,10),guide:String(r.GUIA||r.Guia||r.guia||''),type:String(r.NOVEDAD||r.Novedad||r.GESTION||r.Gestión||'Novedad importada'),status:'Abierta',lastUpdate:new Date().toISOString()});created++;});saveState();renderNovelties();toast(`${created} novedades asignadas`);}catch(e){alert('No se pudo importar: '+e.message);}}
function extractPhone(r){for(const [k,v] of Object.entries(r)){if(/telefono|teléfono|celular|phone/i.test(k)&&v)return String(v);}return'';}
function extractDate(r){for(const [k,v] of Object.entries(r)){if(/fecha/i.test(k)&&v){const d=new Date(v);if(!Number.isNaN(d))return d.toISOString().slice(0,10);}}return'';}
function digits(x){return String(x||'').replace(/\D/g,'').slice(-10);}
function manageNovelty(id){const n=state.novelties.find(x=>x.id===id);if(!n)return;const allowed=isAdmin()?'Abierta|En gestión|Esperando respuesta externa|Resuelta pendiente de validación|Cerrada':'Abierta|En gestión|Esperando respuesta externa|Resuelta pendiente de validación';const st=prompt(`Estado: ${n.status}\nOpciones: ${allowed}`,n.status);if(!st)return;if(st==='Cerrada'&&!isAdmin()){toast('Solo administración puede cerrar');return;}n.status=st;n.lastUpdate=new Date().toISOString();saveState();renderNovelties();toast('Novedad actualizada');}

function renderReports(){
  const ts=todaySales(),confirmed=ts.filter(s=>s.status==='Confirmada');const total=ts.reduce((a,s)=>a+Number(s.price||0),0);const bySource=groupCount(ts,'source');const byWh=groupCount(confirmed,'warehouse');
  el('view-reports').innerHTML=`<div class="page-title"><div><h1>Dashboard en vivo</h1><p>Marketing ve ventas creadas del día calendario. El cierre final se consolida a las 18:00.</p></div><span class="tag green">EN VIVO</span></div><div class="cards">${kpi('Ventas creadas',ts.length,'hoy')}${kpi('Confirmadas',confirmed.length,'hoy')}${kpi('Tasa confirmación',teamConfirmRate()+'%','equipo')}${kpi('Facturación creada',money(total),'valor bruto')}${kpi('Garantías abiertas',state.guarantees.filter(g=>g.status!=='Cerrada').length,'operación')}${kpi('Novedades abiertas',state.novelties.filter(n=>n.status!=='Cerrada').length,'logística')}</div><div class="grid-equal" style="margin-top:14px"><div class="panel"><div class="panel-head"><h3>Origen de ventas</h3></div><div class="panel-body">${objectStatLines(bySource)}</div></div><div class="panel"><div class="panel-head"><h3>Confirmadas por bodega</h3></div><div class="panel-body">${objectStatLines(byWh)}</div></div></div><div class="panel admin-only" style="margin-top:14px"><div class="panel-head"><h3>Información administrativa</h3></div><div class="panel-body"><div class="statline"><span>Ventas pendientes de corte</span><b>${confirmed.filter(s=>!s.cutId).length}</b></div><div class="statline"><span>Cortes ejecutados</span><b>${state.cuts.length}</b></div><div class="statline"><span>Inventario registrado</span><b>${state.inventory.length} SKUs</b></div></div></div>`;
}
function groupCount(arr,key){return arr.reduce((a,x)=>{const k=x[key]||'Sin definir';a[k]=(a[k]||0)+1;return a;},{});}
function objectStatLines(o){const e=Object.entries(o);return e.length?e.sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="statline"><span>${esc(k)}</span><b>${v}</b></div>`).join(''):'<div class="muted">Sin datos.</div>';}

function renderTeam(){
  const metrics=ADVISORS.map(name=>{const all=state.sales.filter(s=>s.advisor===name),valid=all.filter(s=>s.status!=='Duplicado'&&s.status!=='Perdido – datos inválidos'),conf=valid.filter(s=>s.status==='Confirmada');return {name,assigned:all.length,valid:valid.length,confirmed:conf.length,rate:valid.length?Math.round(conf.length/valid.length*100):0,guar:state.guarantees.filter(g=>g.advisor===name&&g.status!=='Cerrada').length,nov:state.novelties.filter(n=>n.advisor===name&&n.status!=='Cerrada').length};});
  el('view-team').innerHTML=`<div class="page-title"><div><h1>Equipo / KPIs</h1><p>El tablero global es visible para todos. La evaluación individual solo es visible para administración y gerencia.</p></div></div><div class="cards">${kpi('Equipo',ADVISORS.length,'asesores')}${kpi('Tasa global',teamConfirmRate()+'%','confirmación')}${kpi('Ventas hoy',todaySales().length,'creadas')}${kpi('Confirmadas hoy',todaySales().filter(s=>s.status==='Confirmada').length,'equipo')}${kpi('Garantías',state.guarantees.filter(g=>g.status!=='Cerrada').length,'abiertas')}${kpi('Novedades',state.novelties.filter(n=>n.status!=='Cerrada').length,'abiertas')}</div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Tablero global del equipo</h3></div><div class="panel-body"><div class="mini-grid">${metrics.map(m=>`<div class="mini"><small>Participación</small><b>${m.assigned}</b><div class="muted">ventas asignadas</div></div>`).join('')}</div></div></div><div class="panel admin-only" style="margin-top:14px"><div class="panel-head"><h3>Métricas individuales · Solo administración</h3><div class="spacer"></div><span class="tag dark">PRIVADO</span></div><div class="table-wrap"><table class="kpi-table"><thead><tr><th>Asesor</th><th>Asignadas</th><th>Gestionadas válidas</th><th>Confirmadas</th><th>Tasa</th><th>Garantías</th><th>Novedades</th></tr></thead><tbody>${metrics.map(m=>`<tr><td><b>${m.name}</b></td><td>${m.assigned}</td><td>${m.valid}</td><td>${m.confirmed}</td><td><b>${m.rate}%</b></td><td>${m.guar}</td><td>${m.nov}</td></tr>`).join('')}</tbody></table></div></div>`;
}
function renderConfig(){if(!isAdmin()){el('view-config').innerHTML='<div class="page-title"><h1>Sin acceso</h1></div>';return;}el('view-config').innerHTML=`<div class="page-title"><div><h1>Configuración operativa</h1><p>Reglas base de la primera versión.</p></div></div><div class="grid-equal"><div class="panel"><div class="panel-head"><h3>Horario</h3></div><div class="panel-body"><div class="statline"><span>Lunes–sábado</span><b>08:00–18:00</b></div><div class="statline"><span>Domingo</span><b>Sin alertas</b></div><div class="statline"><span>Venta sin gestión</span><b>5 min amarilla / 10 min roja</b></div></div></div><div class="panel"><div class="panel-head"><h3>Recuperación</h3></div><div class="panel-body"><div class="statline"><span>Intentos</span><b>3</b></div><div class="statline"><span>Secuencia</span><b>Mañana → tarde → mañana siguiente</b></div><div class="statline"><span>WhatsApp</span><b>Después de cada intento</b></div></div></div><div class="panel"><div class="panel-head"><h3>Bodegas</h3></div><div class="panel-body"><div class="statline"><span>Regla 1</span><b>Más cercana + pedido completo</b></div><div class="statline"><span>Regla 2</span><b>Otra bodega con pedido completo</b></div><div class="statline"><span>Dividir</span><b>Solo excepción manual extrema</b></div></div></div><div class="panel"><div class="panel-head"><h3>Futuro</h3></div><div class="panel-body"><div class="statline"><span>Hoko API</span><b>Pendiente</b></div><div class="statline"><span>LogiGho API</span><b>Pendiente</b></div><div class="statline"><span>Telefonía</span><b>No implementar aún</b></div><div class="statline"><span>Voz IA</span><b>No implementar aún</b></div></div></div></div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Datos locales</h3></div><div class="panel-body"><p class="muted">Solo para pruebas. Al conectar Supabase, la información se compartirá entre todos los usuarios.</p><button class="btn red" onclick="resetDemo()">Restablecer datos de prueba</button></div></div>`;}
function resetDemo(){if(confirm('¿Restablecer todos los datos locales de esta versión de prueba?')){state=clone(DEFAULT_STATE);saveState();render();toast('Datos restablecidos');}}

function buildAlerts(){const alerts=[];const now=Date.now();const mine=s=>!isAdvisor()||s.advisor===session.name;state.sales.filter(s=>mine(s)&&s.status==='Nueva').forEach(s=>{const mins=(now-new Date(s.createdAt).getTime())/60000;if(mins>=10)alerts.push({level:'red',title:`${s.id} sin gestionar`,text:`${Math.floor(mins)} min sin movimiento. Debe atenderse de inmediato.`});else if(mins>=5)alerts.push({level:'amber',title:`${s.id} necesita gestión`,text:`${Math.floor(mins)} min desde la asignación.`});});state.guarantees.filter(g=>mine(g)&&g.status!=='Cerrada').forEach(g=>{const hrs=(now-new Date(g.lastUpdate))/36e5;if(hrs>=48)alerts.push({level:'red',title:`Garantía ${g.id} vencida`,text:'Más de 48 horas sin gestión registrada.'});else if(hrs>=24)alerts.push({level:'amber',title:`Actualizar garantía ${g.id}`,text:'Corresponde actualización al cliente.'});});state.novelties.filter(n=>mine(n)&&n.status!=='Cerrada').forEach(n=>{const hrs=(now-new Date(n.lastUpdate))/36e5;if(hrs>=24)alerts.push({level:'red',title:`Novedad ${n.id} sin resolver`,text:'Supera 24 horas sin gestión.'});});Object.entries(state.inventorySources).filter(([,v])=>!v).forEach(([w])=>alerts.push({level:'amber',title:`Stock pendiente: ${w}`,text:'Carga el archivo para trabajar con disponibilidad real.'}));return alerts;}
function alertHtml(a){return `<div class="alert ${a.level}"><strong>${esc(a.title)}</strong><div>${esc(a.text)}</div></div>`;}
function renderAI(){const p=el('aiPanel');if(!p)return;const alerts=buildAlerts();p.innerHTML=`<div class="ai-head"><span class="planet" style="width:27px;height:27px;border-width:4px"></span><b>INVICTO I.A.</b><button class="close" onclick="toggleAI()">×</button></div><div class="ai-body">${alerts.map(a=>`<div class="ai-item ${a.level}"><b>${esc(a.title)}</b><br>${esc(a.text)}${a.level==='red'?'<button class="btn light sm" onclick="ackAI(this)">Revisar / resolver</button>':''}</div>`).join('')||'<div class="ai-item info"><b>Sin alertas.</b><br>La operación no presenta eventos relevantes en este momento.</div>'}</div>`;}
function toggleAI(){el('aiPanel').classList.toggle('open');}
function ackAI(btn){btn.textContent='Marcada para gestión';btn.disabled=true;}

window.addEventListener('load',render);
