/* INVICTO OPS v31 · rendimiento unificado y medición minuciosa por asesor */
const OPS_PERFORMANCE_VERSION_V31='31.0';
const OPS_PERFORMANCE_CUTOVER_V31=Date.parse('2026-09-15T05:00:00Z');
let perfDataV31=null;
let perfFollowV31=null;
let perfDateV31='';
let perfBusyV31=false;
let perfAdvisorV31='';
let perfStatusV31='';
let perfSearchV31='';

function perfTodayV31(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function perfDateTimeV31(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('es-CO',{timeZone:'America/Bogota',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}
function perfMinutesV31(v){if(v==null)return '—';v=Number(v);if(v<60)return `${v.toFixed(v<10?1:0)} min`;if(v<1440)return `${(v/60).toFixed(1)} h`;return `${(v/1440).toFixed(1)} d`}
function perfPctV31(v){return v==null?'—':`${Number(v).toFixed(1)}%`}
function perfStatusLabelV31(st=''){return ({nueva:'Nueva',asignada:'Asignada',en_gestion:'En gestión',no_contesta:'No contesta',seguimiento_programado:'Seguimiento programado',pendiente_stock:'Pendiente stock',confirmada:'Confirmada',perdida:'Perdida',duplicada:'Duplicada · no contabiliza',cancelada:'Cancelada'})[st]||st||'—'}
function perfStatusClassV31(st=''){if(st==='confirmada')return 'green';if(['perdida','cancelada'].includes(st))return 'red';if(st==='duplicada')return 'gray';if(['no_contesta','seguimiento_programado','pendiente_stock'].includes(st))return 'amber';return 'blue'}
function perfTaskV31(r){if(r.followup_overdue)return 'ATENDER AHORA · seguimiento vencido';return ({nueva:'Contactar cliente',asignada:'Primer contacto',en_gestion:'Continuar gestión',no_contesta:'Reintentar contacto',seguimiento_programado:'Cumplir seguimiento',pendiente_stock:'Validar stock',confirmada:'Terminada · confirmada',perdida:'Terminada · perdida',duplicada:'No gestionar · duplicada',cancelada:'Terminada · cancelada'})[r.status]||'Revisar'}
function perfNextV31(r){if(r.followup_overdue)return 'VENCIDO';if(r.next_followup_at)return perfDateTimeV31(r.next_followup_at);if(['confirmada','perdida','duplicada','cancelada'].includes(r.status))return 'Finalizada';return perfTaskV31(r)}

function perfStylesV31(){if(document.getElementById('perfStylesV31'))return;const s=document.createElement('style');s.id='perfStylesV31';s.textContent=`
.perf-hero-v31{display:flex;gap:16px;align-items:flex-start;justify-content:space-between}.perf-hero-v31 h1{margin:3px 0 5px}.perf-actions-v31{display:flex;gap:8px;flex-wrap:wrap}.perf-zero-v31{padding:14px 16px;border-radius:14px;background:#eef8f3;border:1px solid #c7ead7;margin-bottom:14px;color:#19613e}.perf-cards-v31{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:10px;margin:14px 0}.perf-card-v31{background:white;border:1px solid #e4e8ef;border-radius:16px;padding:14px}.perf-card-v31 small{display:block;color:#707b91}.perf-card-v31 b{display:block;font-size:25px;margin:4px 0;color:#09132a}.perf-card-v31 span{font-size:12px;color:#7a8497}.perf-section-v31{margin-top:14px}.perf-table-v31{min-width:1800px}.perf-table-v31 td,.perf-table-v31 th{white-space:nowrap}.perf-advisor-name-v31{display:flex;align-items:center;gap:8px}.perf-dot-v31{width:9px;height:9px;border-radius:50%;background:#19a66c}.perf-bad-v31{font-weight:900;color:#bd3e2c}.perf-good-v31{font-weight:900;color:#148158}.perf-muted-v31{color:#718096;font-size:12px}.perf-toolbar-v31{display:flex;gap:8px;flex-wrap:wrap}.perf-toolbar-v31 .search{min-width:180px}.perf-history-back-v31{position:fixed;inset:0;background:rgba(2,16,68,.48);z-index:99960}.perf-history-v31{position:fixed;right:0;top:0;bottom:0;width:min(620px,94vw);background:#fff;z-index:99961;box-shadow:-16px 0 50px rgba(2,16,68,.22);overflow:auto;padding:24px}.perf-history-v31 h2{margin:3px 0}.perf-history-head-v31{display:flex;gap:12px;align-items:flex-start;border-bottom:1px solid #e8ebf0;padding-bottom:16px}.perf-history-head-v31 button{margin-left:auto}.perf-timeline-v31{margin-top:20px}.perf-event-v31{position:relative;padding:0 0 18px 24px;border-left:2px solid #e5e9f0;margin-left:7px}.perf-event-v31:before{content:'';position:absolute;left:-7px;top:2px;width:12px;height:12px;border-radius:50%;background:#091c5a}.perf-event-v31 small,.perf-event-v31 p{color:#6d7890}.perf-event-v31 b{display:block;margin:3px 0}.perf-advisor-detail-v31{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:15px}.perf-advisor-detail-v31>div{border:1px solid #e6eaf0;border-radius:13px;padding:12px}.perf-advisor-detail-v31 small{display:block;color:#6d7890}.perf-advisor-detail-v31 b{font-size:18px}.perf-activity-v31{max-height:520px;overflow:auto}.perf-activity-row-v31{display:grid;grid-template-columns:130px 150px 180px 1fr;gap:10px;padding:11px 14px;border-bottom:1px solid #edf0f4}.perf-activity-row-v31:last-child{border-bottom:0}
@media(max-width:1200px){.perf-cards-v31{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.perf-cards-v31{grid-template-columns:repeat(2,1fr)}.perf-hero-v31{display:block}.perf-actions-v31{margin-top:10px}.perf-advisor-detail-v31{grid-template-columns:repeat(2,1fr)}.perf-activity-row-v31{grid-template-columns:1fr}}
`;document.head.appendChild(s)}

async function loadPerformanceV31(force=false){
  if(perfBusyV31)return;if(!perfDateV31)perfDateV31=perfTodayV31();
  if(!force&&perfDataV31?.date===perfDateV31){renderPerformanceV31();return}
  perfBusyV31=true;const host=el('view-performance');if(host)host.innerHTML='<div class="page-title"><div><h1>Rendimiento</h1><p>Cargando medición detallada…</p></div></div>';
  try{
    const [p,f]=await Promise.all([
      invictoSupabaseV12.rpc('get_unified_advisor_performance_v31',{p_date:perfDateV31}),
      invictoSupabaseV12.rpc('get_ops_followup_board',{p_date:perfDateV31})
    ]);
    if(p.error)throw p.error;if(f.error)throw f.error;perfDataV31=p.data||{};perfFollowV31=f.data||{};renderPerformanceV31();
  }catch(e){console.error('performance v31',e);if(host)host.innerHTML=`<div class="page-title"><div><h1>Rendimiento</h1><p>No se pudo cargar.</p></div></div><div class="blocking">${esc(e?.message||e)}</div>`}
  finally{perfBusyV31=false}
}
window.refreshPerformanceV31=function(){perfDataV31=null;perfFollowV31=null;loadPerformanceV31(true)};
window.changePerformanceDateV31=function(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return;perfDateV31=v;perfDataV31=null;perfFollowV31=null;loadPerformanceV31(true)};
window.setPerfFilterV31=function(k,v){if(k==='advisor')perfAdvisorV31=v;if(k==='status')perfStatusV31=v;if(k==='search')perfSearchV31=v;renderPerformanceV31()};

function perfFilteredSalesV31(){const rows=perfDataV31?.sales||[],q=String(perfSearchV31||'').trim().toLowerCase();return rows.filter(r=>(!perfAdvisorV31||r.advisor_id===perfAdvisorV31)&&(!perfStatusV31||r.status===perfStatusV31)&&(!q||[r.order,r.customer_name,r.customer_phone,r.customer_city,r.advisor,perfTaskV31(r)].some(x=>String(x||'').toLowerCase().includes(q))))}
function perfCardV31(label,value,sub=''){return `<div class="perf-card-v31"><small>${esc(label)}</small><b>${value}</b><span>${esc(sub)}</span></div>`}

function perfAdvisorTableV31(rows){return `<div class="panel perf-section-v31"><div class="panel-head"><div><h3>Medición completa por asesor</h3><div class="muted">Cada dato comienza desde el 15 de septiembre a las 00:00. Duplicados no afectan conversión.</div></div></div><div class="table-wrap"><table class="perf-table-v31"><thead><tr><th>Asesor</th><th>Asignadas</th><th>Arrastre</th><th>Carga total</th><th>Gestionadas</th><th>Sin tocar</th><th>Pendientes</th><th>Intentos</th><th>Intentos/gestión</th><th>Seguimientos</th><th>Vencidos</th><th>Confirmadas</th><th>Perdidas</th><th>Canceladas</th><th>Duplicadas</th><th>Conversión</th><th>% gestión</th><th>1ª respuesta prom.</th><th>Máx. 1ª resp.</th><th>≤5 min</th><th>≤10 min</th><th>Manuales</th><th>Unidades conf.</th><th>Valor conf.</th><th>Amarillas</th><th>Rojas</th><th>Última actividad</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><div class="perf-advisor-name-v31"><span class="perf-dot-v31"></span><b>${esc(r.advisor)}</b></div></td><td>${r.assigned}</td><td>${r.carryover}</td><td><b>${r.workload}</b></td><td>${r.managed}</td><td class="${r.untouched?'perf-bad-v31':''}">${r.untouched}</td><td>${r.pending}</td><td><b>${r.attempts}</b></td><td>${Number(r.avg_attempts_per_managed||0).toFixed(2)}</td><td>${r.followups}</td><td class="${r.overdue?'perf-bad-v31':''}">${r.overdue}</td><td class="perf-good-v31">${r.confirmed}</td><td>${r.lost}</td><td>${r.cancelled}</td><td>${r.duplicates}</td><td><b>${perfPctV31(r.conversion)}</b></td><td>${perfPctV31(r.management_rate)}</td><td>${perfMinutesV31(r.avg_first_response_minutes)}</td><td>${perfMinutesV31(r.max_first_response_minutes)}</td><td>${perfPctV31(r.first_response_5m_pct)}</td><td>${perfPctV31(r.first_response_10m_pct)}</td><td>${r.manual_sales}</td><td>${r.confirmed_units}</td><td><b>${money(r.confirmed_value)}</b></td><td>${r.yellow}</td><td class="${r.red?'perf-bad-v31':''}">${r.red}</td><td>${perfDateTimeV31(r.last_activity_at)}</td><td><button class="btn light sm" onclick="openAdvisorPerformanceV31('${r.id}')">Detalle</button></td></tr>`).join('')||'<tr><td colspan="28" class="muted">Sin asesores para esta fecha.</td></tr>'}</tbody></table></div></div>`}

window.openAdvisorPerformanceV31=function(id){const r=(perfDataV31?.advisors||[]).find(x=>x.id===id);if(!r)return;document.getElementById('perfHistoryWrapV31')?.remove();const w=document.createElement('div');w.id='perfHistoryWrapV31';const st=r.status_breakdown||{};w.innerHTML=`<div class="perf-history-back-v31" onclick="closePerfModalV31()"></div><aside class="perf-history-v31"><div class="perf-history-head-v31"><div><div class="eyebrow">DETALLE DE ASESOR</div><h2>${esc(r.advisor)}</h2><div class="muted">${esc(perfDataV31.date||'')} · medición INVICTO OPS</div></div><button class="btn light sm" onclick="closePerfModalV31()">×</button></div><div class="perf-advisor-detail-v31">${[
['Asignadas',r.assigned],['Arrastre',r.carryover],['Carga total',r.workload],['Gestionadas',r.managed],['Sin tocar',r.untouched],['Pendientes',r.pending],['Intentos',r.attempts],['Prom. intentos/gestión',Number(r.avg_attempts_per_managed||0).toFixed(2)],['Seguimientos',r.followups],['Vencidos',r.overdue],['Confirmadas',r.confirmed],['Perdidas',r.lost],['Canceladas',r.cancelled],['Duplicadas',r.duplicates],['Conversión',perfPctV31(r.conversion)],['% gestión',perfPctV31(r.management_rate)],['1ª respuesta promedio',perfMinutesV31(r.avg_first_response_minutes)],['1ª respuesta máxima',perfMinutesV31(r.max_first_response_minutes)],['Respondidas ≤5 min',perfPctV31(r.first_response_5m_pct)],['Respondidas ≤10 min',perfPctV31(r.first_response_10m_pct)],['Ventas manuales',r.manual_sales],['Unidades confirmadas',r.confirmed_units],['Valor confirmado',money(r.confirmed_value)],['Alertas',`${r.yellow} amarillas · ${r.red} rojas`]
].map(x=>`<div><small>${esc(x[0])}</small><b>${x[1]}</b></div>`).join('')}</div><div class="panel" style="margin-top:15px"><div class="panel-head"><h3>Tareas abiertas por estado</h3></div><div class="panel-body">${Object.entries(st).map(([k,v])=>`<div class="statline"><span>${esc(perfStatusLabelV31(k))}</span><b>${v}</b></div>`).join('')||'<div class="muted">Sin tareas abiertas.</div>'}</div></div></aside>`;document.body.appendChild(w)};
window.closePerfModalV31=function(){document.getElementById('perfHistoryWrapV31')?.remove()};

function perfSalesTableV31(rows){const statuses=[...new Set((perfDataV31?.sales||[]).map(x=>x.status).filter(Boolean))],advisors=perfDataV31?.advisors||[];return `<div class="panel perf-section-v31"><div class="panel-head"><div><h3>Venta por venta · tarea y gestión</h3><div class="muted">Quién la tiene, qué ha hecho, tiempos y qué debe hacer después.</div></div><div class="spacer"></div><span class="tag blue">${rows.length} visibles</span></div><div class="panel-head"><div class="perf-toolbar-v31"><input class="search" placeholder="Pedido, cliente, teléfono, ciudad o tarea…" value="${esc(perfSearchV31)}" oninput="setPerfFilterV31('search',this.value)">${perfDataV31?.can_view_all?`<select class="search" onchange="setPerfFilterV31('advisor',this.value)"><option value="">Todos los asesores</option>${advisors.map(a=>`<option value="${a.id}" ${a.id===perfAdvisorV31?'selected':''}>${esc(a.advisor)}</option>`).join('')}</select>`:''}<select class="search" onchange="setPerfFilterV31('status',this.value)"><option value="">Todos los estados</option>${statuses.map(st=>`<option value="${st}" ${st===perfStatusV31?'selected':''}>${esc(perfStatusLabelV31(st))}</option>`).join('')}</select></div></div><div class="table-wrap"><table class="perf-table-v31"><thead><tr><th>Pedido</th><th>Cliente</th><th>Asesor</th><th>Recibida</th><th>Tarea actual</th><th>Estado</th><th>Intentos hoy</th><th>Intentos total</th><th>1ª respuesta</th><th>Última gestión</th><th>Próxima acción</th><th>Sin gestión</th><th>Manual</th><th>Unidades</th><th>Valor</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.order||'—')}</b>${r.carryover_open?'<div><span class="tag amber">ARRASTRE</span></div>':''}</td><td><b>${esc(r.customer_name||'Sin nombre')}</b><div class="perf-muted-v31">${esc(r.customer_phone||'')} · ${esc(r.customer_city||'')}</div></td><td><b>${esc(r.advisor||'—')}</b></td><td>${perfDateTimeV31(r.received_at)}</td><td class="${r.followup_overdue?'perf-bad-v31':''}"><b>${esc(perfTaskV31(r))}</b></td><td><span class="tag ${perfStatusClassV31(r.status)}">${esc(perfStatusLabelV31(r.status))}</span></td><td>${r.attempts_today}</td><td><b>${r.attempts}</b></td><td>${perfMinutesV31(r.first_response_minutes)}</td><td>${perfDateTimeV31(r.last_managed_at)}</td><td class="${r.followup_overdue?'perf-bad-v31':''}">${esc(perfNextV31(r))}</td><td>${perfMinutesV31(r.minutes_without_management)}</td><td>${r.manual?'<span class="tag blue">SÍ</span>':'—'}</td><td>${Number(r.quantity||0)}</td><td>${money(r.total_price||0)}</td><td><button class="btn light sm" onclick="openSalePerformanceV31('${r.id}')">Historial</button></td></tr>`).join('')||'<tr><td colspan="16" class="muted">Sin ventas para estos filtros.</td></tr>'}</tbody></table></div></div>`}

window.openSalePerformanceV31=function(id){const base=(perfDataV31?.sales||[]).find(x=>String(x.id)===String(id));if(!base)return;const f=(perfFollowV31?.sales||[]).find(x=>String(x.id)===String(id));const events=f?.history||base.attempt_events_today||[];document.getElementById('perfHistoryWrapV31')?.remove();const w=document.createElement('div');w.id='perfHistoryWrapV31';w.innerHTML=`<div class="perf-history-back-v31" onclick="closePerfModalV31()"></div><aside class="perf-history-v31"><div class="perf-history-head-v31"><div><div class="eyebrow">BITÁCORA COMPLETA</div><h2>${esc(base.order||'—')}</h2><div class="muted">${esc(base.customer_name||'')} · ${esc(base.advisor||'')}</div></div><button class="btn light sm" onclick="closePerfModalV31()">×</button></div><div class="perf-advisor-detail-v31"><div><small>Estado</small><b>${esc(perfStatusLabelV31(base.status))}</b></div><div><small>Tarea</small><b>${esc(perfTaskV31(base))}</b></div><div><small>Intentos</small><b>${base.attempts}</b></div><div><small>1ª respuesta</small><b>${perfMinutesV31(base.first_response_minutes)}</b></div><div><small>Última gestión</small><b>${perfDateTimeV31(base.last_managed_at)}</b></div><div><small>Próxima acción</small><b>${esc(perfNextV31(base))}</b></div><div><small>Sin gestión</small><b>${perfMinutesV31(base.minutes_without_management)}</b></div><div><small>Origen manual</small><b>${base.manual?'Sí':'No'}</b></div></div><div class="perf-timeline-v31">${events.map(e=>`<div class="perf-event-v31"><small>${perfDateTimeV31(e.at||e.occurred_at)} · ${esc(e.actor||e.advisor||'Sistema')}</small><b>${esc(e.title||(`Intento #${e.attempt||''}`)||'Gestión')}</b>${(e.detail||e.outcome||e.notes)?`<p>${esc(e.detail||[e.outcome,e.notes].filter(Boolean).join(' · '))}</p>`:''}${e.next_followup_at?`<div class="muted">Próxima acción: ${perfDateTimeV31(e.next_followup_at)}</div>`:''}</div>`).join('')||'<div class="muted">Todavía no hay gestiones registradas.</div>'}</div></aside>`;document.body.appendChild(w)};

function perfActivityV31(rows){return `<div class="panel perf-section-v31"><div class="panel-head"><div><h3>Bitácora del día</h3><div class="muted">Secuencia cronológica de asignaciones e intentos realizados.</div></div><div class="spacer"></div><span class="tag gray">${rows.length} eventos</span></div><div class="perf-activity-v31">${rows.map(e=>`<div class="perf-activity-row-v31"><b>${perfDateTimeV31(e.at)}</b><span>${esc(e.advisor||'Sistema')}</span><span><b>${esc(e.order||'—')}</b></span><span>${e.kind==='assigned'?'Venta recibida y asignada':`Intento #${e.attempt||''} · ${esc(e.outcome||'Gestión')}${e.channel?` · ${esc(e.channel)}`:''}${e.notes?` · ${esc(e.notes)}`:''}`}</span></div>`).join('')||'<div class="panel-body muted">Sin actividad todavía.</div>'}</div></div>`}

function renderPerformanceV31(){perfStylesV31();const host=el('view-performance');if(!host)return;if(!perfDataV31){loadPerformanceV31();return}const d=perfDataV31,s=d.summary||{},ad=d.advisors||[],sales=perfFilteredSalesV31(),pre=String(d.date||'')<'2026-09-15';host.innerHTML=`<div class="perf-hero-v31"><div><div class="eyebrow">MEDICIÓN OPERATIVA UNIFICADA · DESDE 15 SEP 2026</div><h1>Rendimiento</h1><p>${d.can_view_all?'Vista total del equipo, usuario por usuario y venta por venta.':'Tu rendimiento, tus tareas y toda tu gestión en una sola pantalla.'}</p></div><div class="perf-actions-v31"><input type="date" class="search" value="${esc(d.date||perfDateV31)}" onchange="changePerformanceDateV31(this.value)"><button class="btn light sm" onclick="refreshPerformanceV31()">↻ Actualizar</button></div></div>${pre?'<div class="perf-zero-v31"><b>Sistema anterior.</b> La medición nueva comienza el 15 de septiembre a las 00:00; esta fecha permanece en 0.</div>':'<div class="perf-zero-v31"><b>Una sola fuente de rendimiento.</b> Día a día, KPIs y reportes de asesores están unificados aquí.</div>'}<div class="perf-cards-v31">${perfCardV31('Asignadas hoy',s.assigned||0,'ventas nuevas')}${perfCardV31('Carga total',(s.workload||0),`${s.carryover||0} arrastre`) }${perfCardV31('Gestionadas',s.managed||0,`${s.untouched||0} sin tocar`)}${perfCardV31('Intentos',s.attempts||0,'acciones registradas')}${perfCardV31('Pendientes',s.pending||0,`${s.overdue||0} vencidas`)}${perfCardV31('Confirmadas',s.confirmed||0,`${s.confirmed_units||0} unidades`)}${perfCardV31('Perdidas',s.lost||0,'ventas válidas')}${perfCardV31('Canceladas',s.cancelled||0,'cerradas')}${perfCardV31('Duplicadas',s.duplicates||0,'no contabilizan')}${perfCardV31('Ventas manuales',s.manual_sales||0,'acreditadas al creador')}${perfCardV31('Alertas amarillas',s.yellow||0,'desde el nuevo sistema')}${perfCardV31('Alertas rojas',s.red||0,'desde el nuevo sistema')}</div>${d.can_view_all?perfAdvisorTableV31(ad):perfAdvisorTableV31(ad)}${perfSalesTableV31(sales)}${perfActivityV31(d.activity||[])}`}
window.renderPerformanceV31=function(){if(!perfDateV31)perfDateV31=perfTodayV31();loadPerformanceV31(false)};

/* Una sola entrada de rendimiento en el menú. */
const renderShellBaseV31=window.renderShell;
window.renderShell=function(){renderShellBaseV31();const nav=document.querySelector('.nav');if(!nav)return;['day-by-day','reports','team'].forEach(v=>nav.querySelector(`[data-view="${v}"]`)?.remove());const content=document.querySelector('.content');if(content&&!el('view-performance')){const s=document.createElement('section');s.id='view-performance';s.className='view';const sales=el('view-sales');content.insertBefore(s,sales||content.firstChild)}if(!nav.querySelector('[data-view="performance"]')){const b=document.createElement('button');b.dataset.view='performance';b.textContent='Rendimiento';b.onclick=()=>switchView('performance');const sales=nav.querySelector('[data-view="sales"]');nav.insertBefore(b,sales||nav.firstChild)}const foot=document.querySelector('.sidebar-foot');if(foot)foot.innerHTML=foot.innerHTML.replace(/Versión\s+[^<]+/,'Versión 31.0')};
const switchViewBaseV31=window.switchView;
window.switchView=function(view,initial=false){if(['day-by-day','reports','team'].includes(view))view='performance';if(view!=='performance')return switchViewBaseV31(view,initial);currentView='performance';document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='performance'));el('view-performance')?.classList.add('active');if(el('topTitle'))el('topTitle').textContent='Rendimiento';window.renderPerformanceV31();if(!initial&&innerWidth<800)el('sidebar')?.classList.remove('open')};

/* Las alertas anteriores al corte desaparecen también de la interfaz. */
window.buildAlerts=function(){if(Date.now()<OPS_PERFORMANCE_CUTOVER_V31)return [];const mine=a=>!isAdvisor()||String(a.user_id||'')===String(session?.id||'');return (state.alerts||[]).filter(a=>a.status==='open'&&mine(a)&&new Date(a.created_at||0).getTime()>=OPS_PERFORMANCE_CUTOVER_V31).map(a=>({severity:a.severity,title:a.title,body:a.body,blocking:a.blocking,created_at:a.created_at}))};
window.alertHtml=function(a){const red=a?.severity==='roja';return `<div class="alert ${red?'red':'yellow'}"><div><b>${esc(a?.title||'Alerta')}</b><div class="muted">${esc(a?.body||'')}</div></div><span class="tag ${red?'red':'amber'}">${red?'ROJA':'AMARILLA'}</span></div>`};

console.info('INVICTO OPS v31 · rendimiento unificado activo');
