function commandItemsV21(q=''){
  const views=[['home','Inicio'],['sales','Ventas'],['recovery','Recuperación'],['inventory','Inventario'],['cuts','Cortes / Guías'],['guarantees','Garantías'],['novelties','Novedades'],['reports','Dashboard'],['team','Equipo / KPIs']];
  const term=q.trim().toLowerCase(),sales=(state.sales||[]).map(s=>({type:'sale',label:`${s.id} · ${s.name}`,sub:`${s.phone||'—'} · ${s.city||'—'} · ${s.status}`,sale:s,score:String(s.id).toLowerCase()===term?100:String(s.id).toLowerCase().startsWith(term)?80:String(s.phone||'').includes(term)?70:String(s.name||'').toLowerCase().includes(term)?60:20})).filter(x=>!term||[x.label,x.sub].join(' ').toLowerCase().includes(term)).sort((a,b)=>b.score-a.score).slice(0,12);
  const nav=views.filter(x=>!term||x[1].toLowerCase().includes(term)).map(x=>({type:'view',view:x[0],label:x[1],sub:'Ir a sección'}));return [...sales,...nav].slice(0,14);
}
window.openCommandV21=function(){let w=document.getElementById('commandV21');if(!w){w=document.createElement('div');w.id='commandV21';document.body.appendChild(w)}w.innerHTML=`<div class="cmd-back-v21" onclick="closeCommandV21()"></div><div class="cmd-box-v21"><div class="cmd-input-v21"><span>⌕</span><input id="cmdInputV21" placeholder="Busca pedido, cliente, teléfono o sección..." oninput="renderCommandResultsV21(this.value)"><kbd>ESC</kbd></div><div id="cmdResultsV21" class="cmd-results-v21"></div><div class="cmd-foot-v21">Atajo: Ctrl/⌘ + K · Enter abre el primer resultado</div></div>`;renderCommandResultsV21('');setTimeout(()=>document.getElementById('cmdInputV21')?.focus(),30)};
window.closeCommandV21=function(){document.getElementById('commandV21')?.remove()};
window.renderCommandResultsV21=function(q){const h=document.getElementById('cmdResultsV21');if(!h)return;const items=commandItemsV21(q);h.innerHTML=items.map((x,i)=>x.type==='sale'?`<button class="cmd-result-v21" data-first="${i===0?'1':''}" onclick="closeCommandV21();switchView('sales');openOrderV20('${esc(x.sale.id)}')"><b>${esc(x.label)}</b><small>${esc(x.sub)}</small></button>`:`<button class="cmd-result-v21" data-first="${i===0?'1':''}" onclick="closeCommandV21();switchView('${x.view}')"><b>${esc(x.label)}</b><small>${esc(x.sub)}</small></button>`).join('')||'<div class="muted" style="padding:18px">Sin resultados.</div>'};

document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommandV21()}else if(e.key==='Escape'){closeCommandV21();if(el('aiPanel')?.classList.contains('open'))toggleAI()}else if(e.key==='Enter'&&document.getElementById('commandV21')&&document.activeElement?.id==='cmdInputV21'){e.preventDefault();document.querySelector('#cmdResultsV21 .cmd-result-v21')?.click()}});

function updateSyncV21(){const t=document.getElementById('syncV21');if(!t)return;const sec=Math.max(0,Math.round((Date.now()-opsLastSyncV21)/1000));t.textContent=sec<10?'Actualizado ahora':sec<60?`Hace ${sec}s`:`Hace ${Math.floor(sec/60)}m`;t.className='sync-v21 '+(sec>120?'stale':'')}
function installSmartFallbackV21(){if(window.__invictoFallbackV13){clearInterval(window.__invictoFallbackV13);window.__invictoFallbackV13=null}if(!window.__invictoSmartFallbackV21){window.__invictoSmartFallbackV21=setInterval(()=>{if(session&&document.visibilityState==='visible')hydrateOpsV13(true).catch(console.error)},90000);document.addEventListener('visibilitychange',()=>{if(session&&document.visibilityState==='visible'&&Date.now()-opsLastSyncV21>60000)hydrateOpsV13(true).catch(console.error)})}}
const hydrateBaseV21=window.hydrateOpsV13;
window.hydrateOpsV13=async function(force=false){const r=await hydrateBaseV21(force);opsLastSyncV21=Date.now();updateSyncV21();installSmartFallbackV21();return r};
window.refreshOpsV21=async function(){const b=document.getElementById('refreshV21');if(b){b.disabled=true;b.textContent='Actualizando…'}try{await hydrateOpsV13(true);switchView(currentView,true);toast('Datos sincronizados')}catch(e){toast('No se pudo actualizar: '+(e.message||e))}finally{if(b){b.disabled=false;b.textContent='↻ Actualizar'}updateSyncV21()}};
setInterval(updateSyncV21,15000);
const renderShellBaseV21=window.renderShell;
window.renderShell=function(){renderShellBaseV21();const top=document.querySelector('.topbar');if(!top)return;const spacer=top.querySelector('.spacer');if(spacer&&!document.getElementById('searchV21'))spacer.insertAdjacentHTML('beforebegin',`<button id="searchV21" class="btn light sm top-search-v21" onclick="openCommandV21()">⌕ Buscar <kbd>⌘K</kbd></button><button id="refreshV21" class="btn light sm" onclick="refreshOpsV21()">↻ Actualizar</button><span id="syncV21" class="sync-v21">Actualizado ahora</span>`);updateSyncV21()};
