/* INVICTO OPS v46 · Recuperación real desde cola importada */
(function(){
  let rows46=[],loading46=false,filter46='pendientes',search46='';
  const e=v=>typeof esc==='function'?esc(v??''):String(v??'');
  const fmt=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('es-CO',{timeZone:'America/Bogota',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})};
  const cash=v=>typeof money==='function'?money(v):Number(v||0).toLocaleString('es-CO');
  const admin=()=>typeof isAdmin==='function'&&isAdmin();
  function norm(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim()}
  function cell(r,names){const ks=Object.keys(r),want=names.map(norm);const k=ks.find(x=>want.includes(norm(x)))||ks.find(x=>want.some(w=>norm(x).includes(w)));return k?r[k]:''}
  function num(v){const n=Number(String(v??'').replace(/[$.\s]/g,'').replace(',','.'));return Number.isFinite(n)?n:0}
  function filtered(){const q=search46.trim().toLowerCase();return rows46.filter(r=>{
    const pending=['pendiente','seguimiento'].includes(r.status);if(filter46==='pendientes'&&!pending)return false;if(filter46==='recuperadas'&&r.status!=='recuperada')return false;if(filter46==='cerradas'&&r.status!=='cerrada')return false;
    return !q||[r.source_id,r.customer_name,r.customer_phone,r.city,r.department,r.advisor_name,r.source_channel,r.source_order_status].some(x=>String(x||'').toLowerCase().includes(q));
  })}
  function status(r){const m={pendiente:['amber','PENDIENTE'],seguimiento:['blue','SEGUIMIENTO'],recuperada:['green','RECUPERADA'],cerrada:['gray','CERRADA']},x=m[r.status]||['gray',r.status];return `<span class="tag ${x[0]}">${e(x[1])}</span>`}
  function actions(r){if(['recuperada','cerrada'].includes(r.status))return '<span class="muted">Finalizada</span>';return `<div style="display:flex;gap:5px;flex-wrap:wrap">
    ${r.customer_phone?`<button class="btn light sm" onclick="recoveryWhatsAppV46('${e(r.customer_phone)}')">WhatsApp</button>`:''}
    <button class="btn light sm" onclick="recoveryActionV46('${r.id}','no_contesta')">No contestó</button>
    <button class="btn light sm" onclick="recoveryActionV46('${r.id}','programar')">Programar</button>
    <button class="btn cyan sm" onclick="recoveryActionV46('${r.id}','recuperada')">Recuperada</button>
    <button class="btn danger-lite sm" onclick="recoveryActionV46('${r.id}','cerrar')">Cerrar</button></div>`}
  function paint(){const host=document.getElementById('view-recovery');if(!host)return;const shown=filtered(),pending=rows46.filter(x=>['pendiente','seguimiento'].includes(x.status)).length,rec=rows46.filter(x=>x.status==='recuperada').length;
    host.innerHTML=`<div class="page-title"><div><div class="eyebrow">RECUPERACIÓN · COLA REAL</div><h1>Recuperación</h1><p>Archivo importado, seguimiento y recuperación sin alterar la asignación comercial original.</p></div>${admin()?`<label class="btn cyan">Cargar archivo de recuperación<input type="file" accept=".xlsx,.xls" hidden onchange="importRecoveryV46(this.files[0])"></label>`:''}</div>
    <div class="cards" style="margin-bottom:14px">${typeof kpi==='function'?kpi('Pendientes',pending,'por gestionar'):''}${typeof kpi==='function'?kpi('Recuperadas',rec,'cerradas con venta'):''}${typeof kpi==='function'?kpi('Total cola',rows46.length,'registros cargados'):''}</div>
    <div class="panel"><div class="panel-head"><div class="toolbar"><input class="search" placeholder="Cliente, teléfono, pedido, ciudad…" value="${e(search46)}" oninput="recoverySearchV46(this.value)"><select class="search" onchange="recoveryFilterV46(this.value)"><option value="pendientes" ${filter46==='pendientes'?'selected':''}>Pendientes</option><option value="recuperadas" ${filter46==='recuperadas'?'selected':''}>Recuperadas</option><option value="cerradas" ${filter46==='cerradas'?'selected':''}>Cerradas</option><option value="todas" ${filter46==='todas'?'selected':''}>Todas</option></select></div><div class="spacer"></div><span class="tag blue">${shown.length} visibles</span><button class="btn light sm" onclick="loadRecoveryV46(true)">↻ Actualizar</button></div>
    ${loading46&&!rows46.length?'<div class="panel-body">Cargando recuperación…</div>':`<div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Canal</th><th>Cliente</th><th>Ciudad</th><th>Estado origen</th><th>Asesor recuperación</th><th>Intentos</th><th>Próxima acción</th><th>Valor</th><th>Gestión</th></tr></thead><tbody>${shown.map(r=>`<tr><td><b>${e(r.source_id)}</b><div class="muted">${r.source_entity_type==='draft_order'?'BORRADOR':'PEDIDO'}${r.linked_sale_id?' · enlazado':''}</div></td><td><span class="tag blue">${e(r.source_channel||'Shopify')}</span></td><td><b>${e(r.customer_name||'Sin nombre')}</b><div class="muted">${e(r.customer_phone||'')}</div></td><td>${e(r.city||'—')}<div class="muted">${e(r.department||'')}</div></td><td>${status(r)}<div class="muted">${e(r.source_order_status||'')}</div></td><td><b>${e(r.advisor_name||'Sin asignar')}</b></td><td>${Number(r.attempts||0)}</td><td>${fmt(r.next_followup_at)}</td><td>${cash(r.total_price||0)}<div class="muted">${Number(r.quantity||0)} uds.</div></td><td>${actions(r)}</td></tr>`).join('')||'<tr><td colspan="10" class="muted">Sin registros para este filtro.</td></tr>'}</tbody></table></div>`}</div>`;
  }
  async function load(force=false){if(loading46||typeof invictoSupabaseV12==='undefined')return;loading46=true;if(currentView==='recovery')paint();try{const {data,error}=await invictoSupabaseV12.rpc('get_recovery_queue_v46');if(error)throw error;rows46=data||[];}catch(err){console.error('recovery v46',err);toast('No se pudo cargar Recuperación: '+(err.message||err));}finally{loading46=false;if(currentView==='recovery')paint();}}
  window.loadRecoveryV46=load;
  window.renderRecovery=function(){paint();load(false)};
  window.recoveryFilterV46=v=>{filter46=v;paint()};
  window.recoverySearchV46=v=>{search46=v;paint();setTimeout(()=>document.querySelector('#view-recovery input.search')?.focus(),0)};
  window.recoveryWhatsAppV46=phone=>{if(typeof openWhatsAppV21==='function')return openWhatsAppV21(phone);let d=String(phone).replace(/\D/g,'');if(d.length===10)d='57'+d;window.open('https://wa.me/'+d,'_blank','noopener')};
  window.recoveryActionV46=async function(id,action){let at=null,notes=null;if(action==='programar'){const raw=prompt('Fecha y hora Colombia (AAAA-MM-DD HH:MM)');if(!raw)return;const d=typeof parseBogotaFollowupV16==='function'?parseBogotaFollowupV16(raw):new Date(raw.replace(' ','T')+':00-05:00');if(!d||Number.isNaN(d.getTime()))return toast('Fecha inválida');at=d.toISOString();notes=prompt('Motivo del seguimiento','Volver a contactar')||'Seguimiento';}if(action==='cerrar'&&!confirm('¿Cerrar este caso de recuperación?'))return;try{const {error}=await invictoSupabaseV12.rpc('update_recovery_queue_v45',{p_id:id,p_action:action,p_next_followup_at:at,p_notes:notes});if(error)throw error;await load(true);toast(action==='recuperada'?'Venta marcada como recuperada':'Recuperación actualizada');}catch(err){console.error(err);toast('No se actualizó: '+(err.message||err))}};
  window.importRecoveryV46=async function(file){if(!file||!admin())return;try{if(typeof XLSX==='undefined')throw new Error('No está disponible el lector Excel');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});if(!raw.length)throw new Error('El archivo está vacío');const payload=raw.map(r=>{const sid=String(cell(r,['ID DEL PEDIDO','ID PEDIDO','PEDIDO','ORDER ID'])||'').trim();const st=String(cell(r,['ESTADO DEL PEDIDO','ESTADO'])||'').trim();const source=String(cell(r,['FUENTE DEL PEDIDO','FUENTE','CANAL'])||'Shopify').trim();const qty=num(cell(r,['CANTIDAD','QTY']));const unit=num(cell(r,['PRECIO UNITARIO','PRECIO','VALOR']));const cod=num(cell(r,['COD','TOTAL DE LA COMPRA','TOTAL']));return {source_id:sid,entity_type:/BORRADOR|DRAFT/i.test(st)?'draft_order':'order',customer_name:String(cell(r,['NOMBRE DEL CLIENTE','NOMBRE DEL DESTINATARIO','CLIENTE','NOMBRE'])||'').trim(),phone:String(cell(r,['NUMERO DE TELEFONO','TELEFONO','CELULAR'])||'').trim(),city:String(cell(r,['COMUNA PUEBLO','CIUDAD','MUNICIPIO'])||'').trim(),department:String(cell(r,['PROVINCIA','DEPARTAMENTO'])||'').trim(),order_status:st,quantity:qty||null,total_price:cod||((qty&&unit)?qty*unit:unit||null),source_channel:/SHOPIFY/i.test(source)?'Shopify':source};}).filter(x=>x.source_id);if(!payload.length)throw new Error('No encontré la columna ID del pedido');toast(`Leyendo ${payload.length} registros de recuperación…`);const {data,error}=await invictoSupabaseV12.rpc('import_recovery_queue_v46',{p_rows:payload,p_source_file:file.name});if(error)throw error;await load(true);toast(`Recuperación cargada · ${Number(data?.inserted||0)} nuevas · ${Number(data?.updated||0)} actualizadas`);}catch(err){console.error('import recovery v46',err);toast('No se pudo cargar Recuperación: '+(err.message||err));}};
  setTimeout(()=>load(true),900);
})();
