/* INVICTO OPS v20 · ventas gestionables + mapeo Shopify confiable */
if(!PRODUCT_CATALOG.medias)PRODUCT_CATALOG.medias={label:'Pack de medias',product:'Medias',material:'textil',style:'pack',sizes:['UNICA'],quantities:[1,3,6,12]};

function sourceCatalogKeyV20(item={}){
  const t=cleanText([item.external_title,item.external_variant,item.external_sku].filter(Boolean).join(' '));
  if(/MEDIA/.test(t))return 'medias';
  if(/BRIEF/.test(t))return 'brief';
  if(/DAMA|MUJER/.test(t))return 'mujer_algodon';
  if(/NI[NÑ]O|KIDS?/.test(t))return 'ninos_estampado';
  if(/ALGODON/.test(t))return 'adulto_algodon';
  if(/ESTAMPADO|ESTAMPADOS|NUEVA COLECCION/.test(t))return 'adulto_estampado';
  if(/LICRA|MICROFIBRA|UNICOLOR/.test(t))return 'adulto_licra';
  return 'adulto_estampado';
}
function sourceSizeV20(item={},catalogKey='adulto_estampado'){
  const p=PRODUCT_CATALOG[catalogKey]||PRODUCT_CATALOG.adulto_estampado;
  const raw=cleanText([item.external_variant,item.external_title].filter(Boolean).join(' / '));
  for(const s of [...p.sizes].sort((a,b)=>b.length-a.length)){
    const token=cleanText(s).replace(/\s/g,'');const compact=raw.replace(/\s/g,'');
    if(compact===token||compact.endsWith('/'+token)||compact.endsWith('-'+token)||new RegExp(`(^|[^A-Z0-9])${token.replace('-','\\-')}([^A-Z0-9]|$)`).test(compact))return s;
  }
  return p.sizes[0];
}
function sourceGroupsV20(s){
  if(s?.groups?.length)return s.groups.map(g=>{const p=PRODUCT_CATALOG[g.catalogKey]||PRODUCT_CATALOG.adulto_estampado;const fallback=p.sizes.includes(g.size)?g.size:p.sizes[0];return {...g,id:g.id||groupId(),qty:Math.max(1,Number(g.qty||(g.units||[]).length||1)),size:fallback,entryMode:g.entryMode||'individual',units:(g.units||[]).map(u=>({...u,size:p.sizes.includes(u.size)?u.size:fallback}))}});
  const src=(s?.sourceItems||[]).filter(x=>Number(x.source_quantity||x.quantity||0)>0);
  if(src.length){return src.map(item=>{const catalogKey=sourceCatalogKeyV20(item),p=PRODUCT_CATALOG[catalogKey],size=sourceSizeV20(item,catalogKey),qty=Math.max(1,Number(item.source_quantity||item.quantity||1));return {id:groupId(),catalogKey,qty,size,entryMode:qty>24?'bulk':'individual',units:[]}})}
  const summary=cleanText(s?.summary||''),catalogKey=/BRIEF/.test(summary)?'brief':/MEDIA/.test(summary)?'medias':/DAMA|MUJER/.test(summary)?'mujer_algodon':/NI[NÑ]O/.test(summary)?'ninos_estampado':/ALGODON/.test(summary)?'adulto_algodon':/UNICOLOR/.test(summary)?'adulto_licra':'adulto_estampado';
  const p=PRODUCT_CATALOG[catalogKey],size=s?.size&&s.size!=='MIXTO'&&p.sizes.includes(s.size)?s.size:p.sizes[0];
  return [{id:groupId(),catalogKey,qty:Math.max(1,Number(s?.qty||6)),size,entryMode:'individual',units:[]}];
}
window.saleGroupsV3=sourceGroupsV20;

function salesPermissionV20(s){return !!s&&(isAdmin()||!isAdvisor()||s.advisorId===session?.id||s.advisor===session?.name)}
function salesStatusOptionsV20(){return ['Nueva','No contesta','Llamar más tarde','Seguimiento futuro','Pendiente stock','Confirmada','Perdido – precio','Perdido – cambió de opinión','Perdido – datos inválidos','Perdido – compró en otro lugar','Perdido – sin cobertura','Perdido – no acepta condición de pago','Duplicado','Cancelada']}
function saleAgeLabelV20(s){const m=Math.max(0,Math.round((Date.now()-new Date(s.lastManagedAt||s.receivedAt||s.createdAt).getTime())/60000));if(m<60)return `${m} min`;return `${Math.floor(m/60)}h ${m%60}m`}
function saleSearchRowsV20(){const q=(el('salesSearch')?.value||'').toLowerCase(),st=el('salesStatus')?.value||'',adv=el('salesAdvisor')?.value||'';return todaySales().filter(s=>(!q||[s.name,s.phone,s.city,s.id,s.advisor,s.summary].join(' ').toLowerCase().includes(q))&&(!st||s.status===st)&&(!adv||s.advisor===adv))}

window.renderSales=function(){
  const data=todaySales(),drafts=data.filter(s=>s.isDraft).length,pending=data.filter(s=>['Nueva','No contesta','Seguimiento futuro','Pendiente stock'].includes(s.status)).length,confirmed=data.filter(s=>s.status==='Confirmada').length;
  el('view-sales').innerHTML=`<div class="page-title"><div><h1>Ventas del día</h1><p>Abre cualquier fila para revisar el pedido. El asesor responsable puede gestionarlo y administración puede intervenir en todos.</p></div><button class="btn cyan" onclick="newOrder()">+ Nueva venta manual</button></div>
  <div class="cards sales-mini-v20">${kpi('Ingresadas',data.length,'hoy')}${kpi('Borradores',drafts,'Shopify')}${kpi('Por gestionar',pending,'activas')}${kpi('Confirmadas',confirmed,'con reserva')}</div>
  <div class="panel" style="margin-top:14px"><div class="panel-head"><div class="toolbar"><input id="salesSearch" class="search" placeholder="Pedido, cliente, teléfono o ciudad..." oninput="filterSales()"><select id="salesStatus" class="search" onchange="filterSales()"><option value="">Todos los estados</option>${salesStatusOptionsV20().map(x=>`<option>${x}</option>`).join('')}</select>${isAdmin()?`<select id="salesAdvisor" class="search" onchange="filterSales()"><option value="">Todos los asesores</option>${ADVISORS.map(x=>`<option>${x}</option>`).join('')}</select>`:''}</div><div class="spacer"></div><span id="salesCountV20" class="tag blue">${data.length} visibles</span></div><div class="table-wrap"><table class="sales-table-v20"><thead><tr><th>Pedido</th><th>Ingreso</th><th>Cliente</th><th>Ciudad</th><th>Asesor</th><th>Estado</th><th>Pedido Shopify</th><th>Valor</th><th>Bodega</th><th></th></tr></thead><tbody id="salesBody"></tbody></table></div></div>`;
  filterSales();
};
window.filterSales=function(){if(!el('salesBody'))return;const rows=saleSearchRowsV20();if(el('salesCountV20'))el('salesCountV20').textContent=`${rows.length} visibles`;el('salesBody').innerHTML=rows.map(s=>{const id=JSON.stringify(String(s.id));return `<tr class="sales-row-v20" onclick='openOrderV20(${id})'><td><b>${esc(s.id)}</b>${s.isDraft?'<div><span class="tag amber">BORRADOR</span></div>':''}<div class="muted">${s.mappingStatus==='pending'?'Sin mapear':'Mapeado'}</div></td><td class="mono">${new Date(s.createdAt).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}<div class="muted">${saleAgeLabelV20(s)}</div></td><td><b>${esc(s.name)}</b><div class="muted mono">${esc(s.phone||'')}</div></td><td>${esc(s.city||'—')}<div class="muted">${esc(s.department||'')}</div></td><td>${esc(s.advisor||'Sin asignar')}</td><td>${statusTag(s.status)}${typeof manualUploadTagV7==='function'?manualUploadTagV7(s):''}</td><td>${esc(s.summary||'—')}<div class="muted">${s.qty||s.sourceQty||0} unidades</div></td><td><b>${money(s.price)}</b></td><td>${esc(s.warehouse||'Por definir')}</td><td><button class="btn navy sm" onclick='event.stopPropagation();openOrderV20(${id})'>Gestionar</button></td></tr>`}).join('')||'<tr><td colspan="10" class="muted">No hay ventas para este filtro.</td></tr>'};

function drawerSourcePanelV20(s){if(!s)return '';const lines=(s.sourceItems||[]).map(x=>`<div class="source-line-v20"><b>${Number(x.source_quantity||x.quantity||1)}×</b><span>${esc(x.external_title||'Producto')}${x.external_variant?` · ${esc(x.external_variant)}`:''}</span>${x.external_sku?`<small>SKU ${esc(x.external_sku)}</small>`:''}</div>`).join('');return `<div class="form-section source-order-v20"><div style="display:flex;gap:8px;align-items:center"><h3 style="margin:0">Pedido recibido</h3><div class="spacer"></div>${s.isDraft?'<span class="tag amber">BORRADOR SHOPIFY</span>':'<span class="tag blue">SHOPIFY</span>'}</div>${lines||`<div class="muted">${esc(s.summary||'Sin detalle de origen')}</div>`}<div class="muted" style="margin-top:8px">Primero ves lo que llegó de Shopify. Debajo defines las referencias exactas que realmente saldrán de inventario.</div></div>`}
function fallbackDrawerV20(s){const d=el('orderDrawer');if(!d)return;d.innerHTML=`<div class="drawer-head"><div><div class="eyebrow">${esc(s?.id||'NUEVA VENTA')}</div><h2>Gestionar venta</h2></div><div class="spacer"></div><button class="close" onclick="closeOrder()">×</button></div><div class="drawer-body">${drawerSourcePanelV20(s)}<div class="form-section"><h3>Gestión comercial</h3><div class="form-grid"><div class="field"><label>Nombre</label><input id="fName" value="${esc(s?.name||'')}"></div><div class="field"><label>Teléfono</label><input id="fPhone" value="${esc(s?.phone||'')}"></div><div class="field"><label>Ciudad</label><input id="fCity" value="${esc(s?.city||'')}"></div><div class="field"><label>Departamento</label><input id="fDepartment" value="${esc(s?.department||'')}"></div><div class="field span2"><label>Dirección</label><input id="fAddress" value="${esc(s?.address||'')}"></div><div class="field"><label>Estado</label><select id="fStatus">${salesStatusOptionsV20().map(x=>`<option ${x===s?.status?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Intentos</label><input id="fAttempts" type="number" min="0" max="3" value="${Number(s?.attempts||0)}"></div><div class="field"><label>Valor</label><input id="fPrice" type="number" value="${Number(s?.price||0)}"></div><div class="field"><label>Pago</label><select id="fPayment"><option>Contraentrega</option><option>Transferencia</option><option>Pago anticipado</option></select></div><div class="field span2"><label>Notas</label><textarea id="fNotes">${esc(s?.notes||'')}</textarea></div></div></div><div class="blocking">La vista avanzada de referencias tuvo un error y se abrió el modo seguro. Puedes guardar la gestión comercial, pero no confirmar stock desde este modo.</div></div><div class="drawer-foot"><button class="btn light" onclick="saveSafeManagementV20()">Guardar gestión</button></div>`}
window.openOrderV20=function(id){editingSaleId=id||null;const s=id?state.sales.find(x=>String(x.id)===String(id)||String(x.dbId)===String(id)):null;if(id&&!s)return toast('No encontré esa venta');try{renderOrderDrawer(s);const body=el('orderDrawer')?.querySelector('.drawer-body');if(s&&body)body.insertAdjacentHTML('afterbegin',drawerSourcePanelV20(s));if(s&&!salesPermissionV20(s)&&isAdvisor()){body?.insertAdjacentHTML('afterbegin','<div class="warning"><b>Solo lectura:</b> esta venta está asignada a otro asesor.</div>');el('orderDrawer')?.querySelectorAll('.drawer-foot button').forEach(b=>b.disabled=true)}el('drawerBack')?.classList.add('open');el('orderDrawer')?.classList.add('open')}catch(e){console.error('openOrderV20',e);fallbackDrawerV20(s);el('drawerBack')?.classList.add('open');el('orderDrawer')?.classList.add('open');toast('Abrí la venta en modo seguro porque la vista avanzada presentó un error')}};
window.openOrder=window.openOrderV20;
window.newOrder=function(){editingSaleId=null;openOrderV20(null)};

function currentItemsV20(){return currentGroups.flatMap(g=>(g.units||[]).map(u=>({...u})).filter(u=>u.variantKey))}
function allUnitsV20(){return currentGroups.flatMap(g=>(g.units||[]).map(u=>({...u}))) }
function summaryV20(){return currentGroups.map(g=>{const p=PRODUCT_CATALOG[g.catalogKey]||PRODUCT_CATALOG.adulto_estampado;const sizes=[...new Set((g.units||[]).map(u=>u.size).filter(Boolean))];return `${Number(g.qty||0)} ${p.label}${sizes.length?` · ${sizes.join('/')}`:''}`}).join(' + ')}
function ownReservedV20(s,vk,w){return (s?.stockReservationItems||[]).filter(x=>x.variantKey===vk&&x.warehouse===w).reduce((a,x)=>a+Number(x.qty||0),0)}
function confirmValidationV20(s,draft){const missing=[];if(!draft.name.trim())missing.push('nombre');if(!draft.phone.trim())missing.push('teléfono');if(!draft.city.trim())missing.push('ciudad');if(!draft.address.trim())missing.push('dirección');if(!draft.warehouse)missing.push('bodega');if(!(draft.price>0))missing.push('valor');const units=allUnitsV20(),qty=currentGroups.reduce((a,g)=>a+Number(g.qty||0),0);if(!qty)missing.push('cantidad');if(units.length!==qty||units.some(u=>!u.variantKey))missing.push('referencias exactas');if(missing.length)return `Falta completar: ${missing.join(', ')}`;const counts=new Map();units.forEach(u=>counts.set(u.variantKey,(counts.get(u.variantKey)||0)+1));for(const [vk,need] of counts){const r=recordV3(vk,draft.warehouse),have=(r?availableStock(r):0)+ownReservedV20(s,vk,draft.warehouse);if(have<need)return `Stock insuficiente para una referencia: necesitas ${need} y hay ${have} disponibles en ${draft.warehouse}.`}return ''}
function collectDraftV20(confirm=false){const existing=editingSaleId?state.sales.find(x=>x.id===editingSaleId):null,units=allUnitsV20(),sizes=[...new Set(units.map(x=>x.size).filter(Boolean))];return {...(existing||{}),name:el('fName')?.value.trim()||'',phone:el('fPhone')?.value.trim()||'',email:existing?.email||'',city:el('fCity')?.value.trim()||'',department:el('fDepartment')?.value.trim()||'',address:el('fAddress')?.value.trim()||'',source:el('fSource')?.value||existing?.source||'manual',advisor:el('fAdvisor')?.value||existing?.advisor||session?.name||'',status:confirm?'Confirmada':(el('fStatus')?.value||existing?.status||'Nueva'),attempts:Number(el('fAttempts')?.value||existing?.attempts||0),qty:currentGroups.reduce((a,g)=>a+Number(g.qty||0),0),price:Number(el('fPrice')?.value||existing?.price||0),payment:el('fPayment')?.value||existing?.payment||'Contraentrega',warehouse:el('fWarehouse')?.value||existing?.warehouse||'',carrier:el('fCarrier')?.value||existing?.carrier||'',deliveryMode:el('fDeliveryMode')?.value||existing?.deliveryMode||'Domicilio',notes:el('fNotes')?.value||'',groups:clone(currentGroups),items:units,size:sizes.length===1?sizes[0]:'MIXTO',summary:summaryV20(),opsData:existing?.opsData||{}}}
function followupFromFormV20(status){if(!['Llamar más tarde','Seguimiento futuro'].includes(status))return null;const def=(()=>{const d=new Date(Date.now()+86400000);return `${new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bogota',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)} 09:00`})();const raw=prompt('Fecha y hora exacta en Colombia (AAAA-MM-DD HH:MM)',def);if(!raw)return false;const d=typeof parseBogotaFollowupV16==='function'?parseBogotaFollowupV16(raw):new Date(raw.replace(' ','T')+':00-05:00');if(!d||Number.isNaN(d.getTime())||d<=new Date()){toast('Fecha/hora de seguimiento inválida');return false}const reason=prompt('Motivo del seguimiento','Llamar más tarde')||'Seguimiento programado';return {at:d.toISOString(),reason}}

window.saveOrderV3=async function(confirm){const existing=editingSaleId?state.sales.find(x=>x.id===editingSaleId):null;if(existing&&!salesPermissionV20(existing))return toast('Esta venta pertenece a otro asesor');const draft=collectDraftV20(confirm);if(confirm){const block=confirmValidationV20(existing,draft);if(block)return toast(block)}const followup=confirm?null:followupFromFormV20(draft.status);if(followup===false)return;try{const buttons=el('orderDrawer')?.querySelectorAll('.drawer-foot button')||[];buttons.forEach(b=>b.disabled=true);toast(confirm?'Confirmando y reservando stock…':'Guardando gestión…');const payload=buildOpsPayloadV13(draft);const {data,error}=await invictoSupabaseV12.rpc('save_ops_sale',{p_sale_id:existing?.dbId||null,p_payload:payload,p_confirm:!!confirm});if(error)throw error;const saleId=data?.sale_id||existing?.dbId;if(followup&&saleId){const {error:e}=await invictoSupabaseV12.rpc('schedule_ops_followup',{p_sale_id:saleId,p_followup_at:followup.at,p_reason:followup.reason});if(e)throw e}const before=Number(existing?.attempts||0),after=Number(draft.attempts||0);if(saleId&&after>before){for(let i=before;i<after;i++){const {error:e}=await invictoSupabaseV12.rpc('record_ops_sale_attempt',{p_sale_id:saleId,p_channel:'manual',p_outcome:draft.status,p_next_followup_at:null,p_notes:'Intento registrado desde gestión de venta'});if(e)throw e}}closeOrder();await hydrateOpsV13(true);switchView('sales');if(typeof renderAI==='function')renderAI();toast(confirm?`Confirmada · ${Number(data?.reserved||0)} unidades reservadas`:'Gestión guardada')}catch(e){console.error('saveOrderV20',e);toast('No se guardó: '+(e.message||e));el('orderDrawer')?.querySelectorAll('.drawer-foot button').forEach(b=>b.disabled=false)}};

window.saveSafeManagementV20=async function(){const s=editingSaleId?state.sales.find(x=>x.id===editingSaleId):null;if(!s?.dbId)return toast('Pedido no encontrado');if(!salesPermissionV20(s))return toast('Esta venta pertenece a otro asesor');try{const draft={...s,name:el('fName')?.value.trim()||s.name,phone:el('fPhone')?.value.trim()||s.phone,city:el('fCity')?.value.trim()||s.city,department:el('fDepartment')?.value.trim()||s.department,address:el('fAddress')?.value.trim()||s.address,status:el('fStatus')?.value||s.status,attempts:Number(el('fAttempts')?.value||s.attempts||0),price:Number(el('fPrice')?.value||s.price||0),payment:el('fPayment')?.value||s.payment,notes:el('fNotes')?.value||s.notes,groups:s.groups||[],items:s.items||[]};const payload=buildOpsPayloadV13(draft);const {error}=await invictoSupabaseV12.rpc('save_ops_sale',{p_sale_id:s.dbId,p_payload:payload,p_confirm:false});if(error)throw error;closeOrder();await hydrateOpsV13(true);switchView('sales');toast('Gestión guardada')}catch(e){console.error(e);toast('No se guardó: '+(e.message||e))}};
