function renderSales(){
  const data=todaySales();
  el('view-sales').innerHTML=`
    <div class="page-title"><div><h1>Ventas del día</h1><p>Las ventas pertenecen al día en que fueron creadas, aunque se confirmen o despachen después.</p></div><button class="btn cyan" onclick="newOrder()">+ Nueva venta manual</button></div>
    <div class="panel"><div class="panel-head"><div class="toolbar"><input id="salesSearch" class="search" placeholder="Buscar cliente, teléfono, ciudad..." oninput="filterSales()"><select id="salesStatus" class="search" onchange="filterSales()"><option value="">Todos los estados</option>${['Nueva','No contesta','Seguimiento futuro','Pendiente stock','Confirmada','Perdido – precio','Perdido – cambió de opinión','Perdido – datos inválidos','Duplicado'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="spacer"></div><span class="tag blue">${data.length} hoy</span></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Hora</th><th>Cliente</th><th>Teléfono</th><th>Ciudad</th><th>Asesor</th><th>Estado</th><th>Intentos</th><th>Pedido</th><th>Valor</th><th>Bodega</th><th>Acción</th></tr></thead><tbody id="salesBody"></tbody></table></div></div>`;
  filterSales();
}
function filterSales(){
  const q=(el('salesSearch')?.value||'').toLowerCase(), st=el('salesStatus')?.value||'';
  const rows=todaySales().filter(s=>(!q||[s.name,s.phone,s.city,s.id,s.advisor].join(' ').toLowerCase().includes(q))&&(!st||s.status===st));
  el('salesBody').innerHTML=rows.map((s,i)=>`<tr><td><b>${i+1}</b><div class="muted mono">${s.id}</div></td><td class="mono">${new Date(s.createdAt).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}</td><td><b>${esc(s.name)}</b></td><td class="mono">${esc(s.phone)}</td><td>${esc(s.city)}</td><td>${esc(s.advisor||'Sin asignar')}</td><td>${statusTag(s.status)}</td><td>${esc(s.attempts??0)}</td><td>${esc(s.summary||'—')}</td><td><b>${money(s.price)}</b></td><td>${esc(s.warehouse||'—')}</td><td><button class="btn light sm" onclick="openOrder('${s.id}')">Abrir</button></td></tr>`).join('')||'<tr><td colspan="12" class="muted">No hay resultados.</td></tr>';
}
function statusTag(st){const c=st==='Confirmada'?'green':st.includes('Perdido')?'red':st==='Nueva'?'blue':st==='Pendiente stock'?'amber':'gray';return `<span class="tag ${c}">${esc(st)}</span>`;}

function renderRecovery(){
  const rows=advisorSales().filter(s=>['No contesta','Seguimiento futuro','Pendiente stock','No recuperado – sin contacto'].includes(s.status));
  el('view-recovery').innerHTML=`<div class="page-title"><div><h1>Recuperación</h1><p>No contesta: 3 intentos. Mañana → tarde 14:00–18:00 → mañana del siguiente día. WhatsApp después de cada intento.</p></div></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>Prioridad</th><th>Cliente</th><th>Teléfono</th><th>Motivo</th><th>Intentos</th><th>Asesor</th><th>Próxima acción</th><th>Acción</th></tr></thead><tbody>${rows.map(s=>`<tr><td>${s.status==='Pendiente stock'?'<span class="tag red">ALTA</span>':'<span class="tag amber">NORMAL</span>'}</td><td><b>${esc(s.name)}</b><div class="muted">${esc(s.city)}</div></td><td>${esc(s.phone)}</td><td>${statusTag(s.status)}</td><td>${esc(s.attempts??0)}/3</td><td>${esc(s.advisor)}</td><td>${s.status==='Pendiente stock'?'Cuando vuelva stock':'Según agenda de recuperación'}</td><td><button class="btn light sm" onclick="openOrder('${s.id}')">Gestionar</button></td></tr>`).join('')||'<tr><td colspan="8" class="muted">Sin recuperaciones pendientes.</td></tr>'}</tbody></table></div></div>`;
}

function newOrder(){editingSaleId=null;openOrder(null);}
function openOrder(id){editingSaleId=id;const s=id?state.sales.find(x=>x.id===id):null;renderOrderDrawer(s);el('drawerBack').classList.add('open');el('orderDrawer').classList.add('open');}
function closeOrder(){el('drawerBack')?.classList.remove('open');el('orderDrawer')?.classList.remove('open');}
function renderOrderDrawer(s){
  const d=el('orderDrawer'); const sale=s||{name:'',phone:'',city:'',department:'',address:'',source:'WhatsApp',advisor:isAdvisor()?session.name:leastLoadedAdvisor(),status:'Nueva',attempts:0,qty:6,price:149900,size:'L',warehouse:'',carrier:'',summary:'',items:[]};
  assortmentMode='estampado';currentUnits=sale.items?.length?sale.items.map(x=>({...x})):[];
  d.innerHTML=`<div class="drawer-head"><div><div class="eyebrow">${s?esc(s.id):'NUEVA VENTA'}</div><h2>${s?'Gestionar venta':'Crear venta manual'}</h2></div><div class="spacer"></div><span id="blockBadge" class="tag red hidden">ALERTA BLOQUEANTE</span><button class="close" onclick="closeOrder()">×</button></div><div class="drawer-body">
    <div class="form-section"><h3>Cliente</h3><div class="form-grid"><div class="field"><label>Nombre completo *</label><input id="fName" value="${esc(sale.name)}"></div><div class="field"><label>Teléfono *</label><input id="fPhone" value="${esc(sale.phone)}"></div><div class="field"><label>Ciudad *</label><input id="fCity" value="${esc(sale.city)}" oninput="updateRecommendation()"></div><div class="field"><label>Departamento *</label><input id="fDepartment" value="${esc(sale.department||'')}"></div><div class="field span2"><label>Dirección exacta con nomenclatura *</label><input id="fAddress" value="${esc(sale.address)}"></div><div class="field"><label>Origen</label><select id="fSource">${['Shopify','WhatsApp','Recuperación','Remarketing','Web','Bot','Presencial'].map(x=>`<option ${sale.source===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Asesor responsable</label><select id="fAdvisor" ${isAdvisor()?'disabled':''}>${ADVISORS.map(x=>`<option ${sale.advisor===x?'selected':''}>${x}</option>`).join('')}</select></div></div></div>
    <div class="form-section"><h3>Resultado / seguimiento</h3><div class="form-grid"><div class="field"><label>Estado</label><select id="fStatus">${['Nueva','No contesta','Llamar más tarde','Seguimiento futuro','Pendiente stock','Confirmada','Perdido – precio','Perdido – cambió de opinión','Perdido – datos inválidos','Perdido – compró en otro lugar','Perdido – sin cobertura','Perdido – no acepta condición de pago','Duplicado'].map(x=>`<option ${sale.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Intentos</label><input id="fAttempts" type="number" min="0" max="3" value="${sale.attempts||0}"></div></div></div>
    <div class="form-section"><h3>Pedido · surtido automático primero</h3><div class="form-grid"><div class="field"><label>Cantidad *</label><select id="fQty" onchange="generateAssortment()">${[3,6,12].map(x=>`<option ${Number(sale.qty)===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Precio *</label><input id="fPrice" type="number" value="${sale.price||149900}"></div><div class="field"><label>Talla *</label><select id="fSize" onchange="generateAssortment()">${['S','M','L','XL','2XL','3XL','4XL','2-4','6-8','10-12','14-16'].map(x=>`<option ${sale.size===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Medio de pago *</label><select id="fPayment"><option>Contraentrega</option><option>Transferencia</option><option>Pago anticipado</option></select></div></div><div class="assortments"><button class="assort active" onclick="pickAssort(this,'estampado')">Surtido estampado adulto</button><button class="assort" onclick="pickAssort(this,'unicolor')">Surtido unicolor adulto</button><button class="assort" onclick="pickAssort(this,'mujer')">Surtido mujer</button><button class="assort" onclick="pickAssort(this,'ninos')">Surtido niños</button><button class="assort" onclick="pickAssort(this,'brief')">Surtido brief</button><button class="assort" onclick="pickAssort(this,'manual')">Selección manual</button></div><div style="display:flex;justify-content:space-between;align-items:center;margin-top:10px"><b>Unidades exactas</b><button class="btn light sm" onclick="generateAssortment()">Regenerar</button></div><div id="units" class="units"></div></div>
    <div class="form-section"><h3>Bodega & despacho</h3><div id="warehouseRec" class="recommend">Calculando recomendación...</div><div class="form-grid" style="margin-top:10px"><div class="field"><label>Bodega elegida *</label><select id="fWarehouse" onchange="renderUnits();checkBlocking()"><option value="">Seleccionar</option>${WAREHOUSES.map(x=>`<option ${sale.warehouse===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Transportadora</label><select id="fCarrier"><option value="">Por definir</option>${TRANSPORTS.map(x=>`<option ${sale.carrier===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field span2"><label>Modalidad</label><select id="fDeliveryMode"><option>Domicilio</option><option>Reclama en oficina</option></select></div></div><div id="blockAlert" class="blocking hidden"></div><div id="warnAlert" class="warning hidden"></div></div>
    <div class="form-section"><h3>Observaciones</h3><div class="field"><textarea id="fNotes" placeholder="Notas del asesor..."></textarea></div></div>
  </div><div class="drawer-foot"><button class="btn light" onclick="saveOrder(false)">Guardar gestión</button><button class="btn cyan" onclick="saveOrder(true)">Confirmar orden + reservar stock</button></div>`;
  if(!currentUnits.length)generateAssortment();else renderUnits();updateRecommendation();checkBlocking();
}
function leastLoadedAdvisor(){const counts=Object.fromEntries(ADVISORS.map(a=>[a,state.sales.filter(s=>isToday(s.createdAt)&&s.advisor===a).length]));return ADVISORS.sort((a,b)=>counts[a]-counts[b])[0];}
function pickAssort(btn,mode){document.querySelectorAll('.assort').forEach(b=>b.classList.remove('active'));btn.classList.add('active');assortmentMode=mode;generateAssortment();}
function compatibleRows(mode,size,warehouse=''){
  const kindMap={estampado:'estampado',unicolor:'unicolor',mujer:'mujer',ninos:'ninos',brief:'brief'};return state.inventory.filter(r=>(!warehouse||r.warehouse===warehouse)&&String(r.size||'').toUpperCase()===String(size).toUpperCase()&&(mode==='manual'||r.kind===kindMap[mode])&&Number(r.stock||0)-Number(r.reserved||0)>0).sort((a,b)=>(b.stock-b.reserved)-(a.stock-a.reserved));
}
function generateAssortment(){if(!el('fQty'))return;const qty=Number(el('fQty').value||6),size=el('fSize').value,wh=el('fWarehouse')?.value||'';let pool=compatibleRows(assortmentMode,size,wh);if(!pool.length)pool=compatibleRows(assortmentMode,size,'');currentUnits=[];const used=new Set();for(let i=0;i<qty;i++){let choice=pool.find(r=>!used.has(r.id)&&Number(r.stock||0)-Number(r.reserved||0)>0)||pool[i%Math.max(1,pool.length)];if(choice){used.add(choice.id);currentUnits.push({inventoryId:choice.id,name:choice.name,variant:choice.variant||choice.name,size:choice.size,warehouse:choice.warehouse,externalId:choice.id});}else currentUnits.push({inventoryId:'',name:assortmentMode==='manual'?'Seleccionar producto':`Surtido ${assortmentMode}`,variant:'Sin inventario cargado',size,warehouse:'',externalId:''});}renderUnits();updateRecommendation();checkBlocking();}
function renderUnits(){const holder=el('units');if(!holder)return;const wh=el('fWarehouse')?.value||'';holder.innerHTML=currentUnits.map((u,i)=>{const matches=compatibleRows(assortmentMode,u.size,wh||'');const rec=state.inventory.find(r=>r.id===u.inventoryId&&(!wh||r.warehouse===wh));const avail=rec?Math.max(0,rec.stock-rec.reserved):0;return `<div class="unit"><span class="n">${i+1}</span><select onchange="changeUnit(${i},this.value)"><option value="${esc(u.inventoryId)}">${esc(u.variant||u.name)}</option>${matches.filter(r=>r.id!==u.inventoryId).slice(0,50).map(r=>`<option value="${esc(r.id)}">${esc(r.variant||r.name)}</option>`).join('')}</select><span>${esc(u.size)}</span><span>${esc(rec?.warehouse||u.warehouse||'Sin bodega')}</span><span class="mono">${esc(rec?.id||u.externalId||'—')}</span><span class="${avail<=3?'stock-low':'stock-ok'}">${rec?avail:'—'}</span></div>`;}).join('');}
function changeUnit(i,id){const r=state.inventory.find(x=>x.id===id);if(r)currentUnits[i]={inventoryId:r.id,name:r.name,variant:r.variant||r.name,size:r.size,warehouse:r.warehouse,externalId:r.id};renderUnits();checkBlocking();}
function updateRecommendation(){if(!el('warehouseRec'))return;const city=(el('fCity')?.value||'').toLowerCase(),size=el('fSize')?.value||'',qty=Number(el('fQty')?.value||0);const preferred=preferredWarehouses(city);const coverage=preferred.map(w=>({w,count:compatibleRows(assortmentMode,size,w).length,stock:compatibleRows(assortmentMode,size,w).reduce((a,r)=>a+(r.stock-r.reserved),0)}));const full=coverage.find(x=>x.count>0&&x.stock>=qty);const rec=full?.w||coverage.sort((a,b)=>b.stock-a.stock)[0]?.w||preferred[0];el('warehouseRec').innerHTML=`<b>Recomendación:</b> ${esc(rec)}. Prioridad: bodega cercana que pueda sacar el pedido completo. Si ninguna puede, ajustar referencias con el cliente antes de considerar una división manual extrema.`;if(!el('fWarehouse').value&&state.inventory.length)el('fWarehouse').value=rec;renderUnits();}
function preferredWarehouses(city){if(/bucaramanga|floridablanca|giron|girón|piedecuesta/.test(city))return ['Bucaramanga','Hoko Medellín','LogiGho Medellín','Hoko Bogotá'];if(/soacha|bogota|bogotá|cundinamarca/.test(city))return ['Hoko Bogotá','Hoko Medellín','LogiGho Medellín','Bucaramanga'];if(/medellin|medellín|bello|envigado|itagui|itagüí|antioquia/.test(city))return ['Hoko Medellín','LogiGho Medellín','Hoko Bogotá','Bucaramanga'];return ['Hoko Bogotá','Hoko Medellín','LogiGho Medellín','Bucaramanga'];}
function checkBlocking(){if(!el('blockAlert'))return false;const alerts=[];if(!el('fName').value.trim()||!el('fPhone').value.trim()||!el('fCity').value.trim()||!el('fAddress').value.trim())alerts.push('Faltan datos obligatorios del cliente.');if(!Number(el('fQty').value)||!Number(el('fPrice').value))alerts.push('Cantidad y precio son obligatorios.');if(!el('fWarehouse').value)alerts.push('Debe seleccionarse una bodega.');if(state.inventory.length===0)alerts.push('No hay inventario cargado. Administración debe subir los stocks antes de confirmar pedidos reales.');const wh=el('fWarehouse').value;if(wh&&state.inventory.length){const ids=currentUnits.map(x=>x.inventoryId);if(ids.some(x=>!x))alerts.push('Hay unidades sin producto definido.');for(const id of ids){const r=state.inventory.find(x=>x.id===id&&x.warehouse===wh);if(!r||r.stock-r.reserved<=0){alerts.push('Una o más unidades no tienen stock disponible en la bodega elegida.');break;}}}
  const box=el('blockAlert'),badge=el('blockBadge');if(alerts.length){box.innerHTML='<b>Alerta roja · debes resolver:</b><br>'+alerts.map(a=>'• '+esc(a)).join('<br>');box.classList.remove('hidden');badge.classList.remove('hidden');return true;}box.classList.add('hidden');badge.classList.add('hidden');return false;}
function saveOrder(confirm){
  if(confirm&&checkBlocking()){toast('Resuelve la alerta roja antes de confirmar');return;}
  const data={name:el('fName').value.trim(),phone:el('fPhone').value.trim(),city:el('fCity').value.trim(),department:el('fDepartment').value.trim(),address:el('fAddress').value.trim(),source:el('fSource').value,advisor:el('fAdvisor').value,status:confirm?'Confirmada':el('fStatus').value,attempts:Number(el('fAttempts').value||0),qty:Number(el('fQty').value),price:Number(el('fPrice').value),size:el('fSize').value,summary:`${el('fQty').value} ${assortmentMode} · ${el('fSize').value}`,warehouse:el('fWarehouse').value,carrier:el('fCarrier').value,items:currentUnits.map(x=>({...x})),payment:el('fPayment').value,deliveryMode:el('fDeliveryMode').value,notes:el('fNotes').value};
  if(editingSaleId){const s=state.sales.find(x=>x.id===editingSaleId);if(confirm&&s.status!=='Confirmada')reserveItems(data.items,data.warehouse);Object.assign(s,data,{confirmedAt:confirm?new Date().toISOString():s.confirmedAt});}
  else{const id='V-'+String(state.sales.length+1).padStart(3,'0');if(confirm)reserveItems(data.items,data.warehouse);state.sales.unshift({id,createdAt:new Date().toISOString(),cutId:null,...data,confirmedAt:confirm?new Date().toISOString():null});}
  saveState();closeOrder();switchView('sales');renderAI();toast(confirm?'Venta confirmada y stock reservado':'Gestión guardada');
}
function reserveItems(items,warehouse){items.forEach(it=>{const r=state.inventory.find(x=>x.id===it.inventoryId&&x.warehouse===warehouse);if(r)r.reserved=Number(r.reserved||0)+1;});}
