/* INVICTO OPS v3 · selector de producto canónico y pedido mixto */
function groupId(){return 'G-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6)}
function defaultGroup(){return {id:groupId(),catalogKey:'adulto_estampado',qty:6,size:'L',units:[]}}
function saleGroupsV3(s){
  if(s?.groups?.length)return s.groups.map(g=>({...g,id:g.id||groupId(),units:(g.units||[]).map(u=>({...u}))}));
  const key=String(s?.summary||'').toLowerCase().includes('algod')?'adulto_algodon':String(s?.summary||'').toLowerCase().includes('unicolor')?'adulto_licra':'adulto_estampado';
  return [{id:groupId(),catalogKey:key,qty:Number(s?.qty||6),size:s?.size&&s.size!=='MIXTO'?s.size:'L',units:[]}];
}
function leastLoadedAdvisor(){const c=Object.fromEntries(ADVISORS.map(a=>[a,state.sales.filter(s=>isToday(s.createdAt)&&s.advisor===a).length]));return [...ADVISORS].sort((a,b)=>c[a]-c[b])[0]}
function renderOrderDrawer(s){
  const d=el('orderDrawer'),sale=s||{name:'',phone:'',city:'',department:'',address:'',source:'WhatsApp',advisor:isAdvisor()?session.name:leastLoadedAdvisor(),status:'Nueva',attempts:0,price:149900,warehouse:'',carrier:'',payment:'Contraentrega',deliveryMode:'Domicilio',notes:''};
  currentGroups=saleGroupsV3(s);
  d.innerHTML=`<div class="drawer-head"><div><div class="eyebrow">${s?esc(s.id):'NUEVA VENTA'}</div><h2>${s?'Gestionar venta':'Crear venta manual'}</h2></div><div class="spacer"></div><span id="blockBadge" class="tag red hidden">ALERTA BLOQUEANTE</span><button class="close" onclick="closeOrder()">×</button></div><div class="drawer-body">
  <div class="form-section"><h3>Cliente</h3><div class="form-grid"><div class="field"><label>Nombre completo *</label><input id="fName" value="${esc(sale.name)}"></div><div class="field"><label>Teléfono *</label><input id="fPhone" value="${esc(sale.phone)}"></div><div class="field"><label>Ciudad *</label><input id="fCity" value="${esc(sale.city)}" oninput="updateRecommendationV3()"></div><div class="field"><label>Departamento</label><input id="fDepartment" value="${esc(sale.department||'')}"></div><div class="field span2"><label>Dirección exacta *</label><input id="fAddress" value="${esc(sale.address)}"></div><div class="field"><label>Origen</label><select id="fSource">${['Shopify','WhatsApp','Recuperación','Remarketing','Web','Bot','Presencial'].map(x=>`<option ${sale.source===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Asesor</label><select id="fAdvisor" ${isAdvisor()?'disabled':''}>${ADVISORS.map(x=>`<option ${sale.advisor===x?'selected':''}>${x}</option>`).join('')}</select></div></div></div>
  <div class="form-section"><h3>Resultado / seguimiento</h3><div class="form-grid"><div class="field"><label>Estado</label><select id="fStatus">${['Nueva','No contesta','Llamar más tarde','Seguimiento futuro','Pendiente stock','Confirmada','Perdido – precio','Perdido – cambió de opinión','Perdido – datos inválidos','Perdido – compró en otro lugar','Perdido – sin cobertura','Perdido – no acepta condición de pago','Duplicado'].map(x=>`<option ${sale.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Intentos</label><input id="fAttempts" type="number" min="0" max="3" value="${sale.attempts||0}"></div></div></div>
  <div class="form-section"><div class="product-section-head"><div><h3>Pedido · producto exacto</h3><p class="muted">El sistema arma un surtido según stock. Luego puedes cambiar cada unidad.</p></div><button class="btn navy sm" onclick="addProductGroupV3()">+ Agregar otro producto</button></div><div id="productGroups"></div><div class="order-total-strip"><div><span>Total unidades</span><b id="orderQtyTotal">0</b></div><div class="field compact"><label>Valor total *</label><input id="fPrice" type="number" value="${sale.price||149900}"></div><div class="field compact"><label>Medio de pago</label><select id="fPayment">${['Contraentrega','Transferencia','Pago anticipado'].map(x=>`<option ${sale.payment===x?'selected':''}>${x}</option>`).join('')}</select></div></div></div>
  <div class="form-section"><h3>Bodega & despacho</h3><div id="warehouseRec" class="recommend">Calculando...</div><div class="form-grid" style="margin-top:10px"><div class="field"><label>Bodega elegida *</label><select id="fWarehouse" onchange="warehouseChangedV3()"><option value="">Seleccionar</option>${WAREHOUSES.map(x=>`<option ${sale.warehouse===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Transportadora</label><select id="fCarrier"><option value="">Por definir</option>${TRANSPORTS.map(x=>`<option ${sale.carrier===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field span2"><label>Modalidad</label><select id="fDeliveryMode">${['Domicilio','Reclama en oficina'].map(x=>`<option ${sale.deliveryMode===x?'selected':''}>${x}</option>`).join('')}</select></div></div><div id="blockAlert" class="blocking hidden"></div></div>
  <div class="form-section"><h3>Observaciones</h3><div class="field"><textarea id="fNotes">${esc(sale.notes||'')}</textarea></div></div></div>
  <div class="drawer-foot"><button class="btn light" onclick="saveOrderV3(false)">Guardar gestión</button><button class="btn cyan" onclick="saveOrderV3(true)">Confirmar orden + reservar stock</button></div>`;
  if(!el('fWarehouse').value&&state.inventory.length)el('fWarehouse').value=chooseWarehouseV3(false)||'';
  currentGroups.forEach(g=>ensureGroupUnitsV3(g,false));renderProductGroupsV3();updateRecommendationV3();checkBlockingV3();
}
function groupProductKeyV3(g){return catalogCanonicalKey(g.catalogKey)}
function rowsForGroupV3(g,w='',availableOnly=true){return state.inventory.filter(r=>r.productKey===groupProductKeyV3(g)&&normalizeSize(r.size)===normalizeSize(g.size)&&(!w||r.warehouse===w)&&(!availableOnly||availableStock(r)>0))}
function variantsForGroupV3(g,w=''){
  const map=new Map();rowsForGroupV3(g,w,true).forEach(r=>{const v=map.get(r.variantKey)||{variantKey:r.variantKey,design:r.design,available:0};v.available+=availableStock(r);map.set(r.variantKey,v)});return [...map.values()].sort((a,b)=>b.available-a.available||String(a.design).localeCompare(String(b.design),'es',{numeric:true}))
}
function recordV3(vk,w){return state.inventory.find(r=>r.variantKey===vk&&r.warehouse===w)||null}
function demandBucketsV3(){const m=new Map();currentGroups.forEach(g=>{const k=groupProductKeyV3(g)+'@@'+normalizeSize(g.size);m.set(k,(m.get(k)||0)+Number(g.qty||0))});return m}
function canAutoFulfillV3(w){for(const [k,need] of demandBucketsV3()){const [pk,size]=k.split('@@'),have=state.inventory.filter(r=>r.warehouse===w&&r.productKey===pk&&normalizeSize(r.size)===size).reduce((a,r)=>a+availableStock(r),0);if(have<need)return false}return true}
function exactCountsV3(){const m=new Map();currentGroups.forEach(g=>(g.units||[]).forEach(u=>{if(u.variantKey)m.set(u.variantKey,(m.get(u.variantKey)||0)+1)}));return m}
function canExactFulfillV3(w){const all=currentGroups.flatMap(g=>g.units||[]);if(!all.length||all.some(u=>!u.variantKey))return false;for(const [vk,n] of exactCountsV3()){const r=recordV3(vk,w);if(!r||availableStock(r)<n)return false}return true}
function coverageV3(w){return currentGroups.reduce((score,g)=>score+Math.min(Number(g.qty||0),rowsForGroupV3(g,w,true).reduce((a,r)=>a+availableStock(r),0)),0)}
function chooseWarehouseV3(exact=true){const p=preferredWarehouses((el('fCity')?.value||'').toLowerCase());if(exact){const w=p.find(canExactFulfillV3);if(w)return w}return p.find(canAutoFulfillV3)||[...p].sort((a,b)=>coverageV3(b)-coverageV3(a))[0]}
function ensureGroupUnitsV3(g,force=false,w=''){
  const p=PRODUCT_CATALOG[g.catalogKey]||PRODUCT_CATALOG.adulto_estampado;g.qty=Number(g.qty||p.quantities[0]);if(!p.sizes.includes(g.size))g.size=p.sizes[0];
  if(!force&&g.units?.length===g.qty&&g.units.every(u=>u.variantKey))return;
  w=w||el('fWarehouse')?.value||chooseWarehouseV3(false)||'';const pool=variantsForGroupV3(g,w).map(v=>({...v,left:v.available})),used=new Set();g.units=[];
  for(let i=0;i<g.qty;i++){let v=pool.find(x=>x.left>0&&!used.has(x.variantKey))||pool.filter(x=>x.left>0).sort((a,b)=>b.left-a.left)[0];if(v){v.left--;used.add(v.variantKey);g.units.push({variantKey:v.variantKey,product:p.product,material:p.material,style:p.style,size:g.size,design:v.design})}else g.units.push({variantKey:'',product:p.product,material:p.material,style:p.style,size:g.size,design:''})}
}
function addProductGroupV3(){const g=defaultGroup();currentGroups.push(g);ensureGroupUnitsV3(g,true);renderProductGroupsV3();updateRecommendationV3();checkBlockingV3()}
function removeProductGroupV3(id){if(currentGroups.length===1)return toast('Debe quedar al menos un producto');currentGroups=currentGroups.filter(g=>g.id!==id);renderProductGroupsV3();updateRecommendationV3();checkBlockingV3()}
function updateGroupV3(id,key,value){const g=currentGroups.find(x=>x.id===id);if(!g)return;if(key==='catalogKey'){g.catalogKey=value;const p=PRODUCT_CATALOG[value];g.qty=p.quantities.includes(Number(g.qty))?Number(g.qty):p.quantities[0];g.size=p.sizes.includes(g.size)?g.size:p.sizes[0]}else if(key==='qty')g.qty=Number(value);else g.size=value;g.units=[];ensureGroupUnitsV3(g,true);renderProductGroupsV3();updateRecommendationV3();checkBlockingV3()}
function regenerateGroupV3(id){const g=currentGroups.find(x=>x.id===id);if(!g)return;g.units=[];ensureGroupUnitsV3(g,true);renderProductGroupsV3();checkBlockingV3()}
function changeUnitV3(id,i,vk){const g=currentGroups.find(x=>x.id===id),p=PRODUCT_CATALOG[g.catalogKey],r=state.inventory.find(x=>x.variantKey===vk);g.units[i]={variantKey:vk,product:p.product,material:p.material,style:p.style,size:g.size,design:r?.design||''};renderProductGroupsV3();updateRecommendationV3();checkBlockingV3()}
function renderProductGroupsV3(){const h=el('productGroups');if(!h)return;const w=el('fWarehouse')?.value||'';h.innerHTML=currentGroups.map((g,i)=>groupHtmlV3(g,i,w)).join('');el('orderQtyTotal').textContent=currentGroups.reduce((a,g)=>a+Number(g.qty||0),0)}
function groupHtmlV3(g,i,w){const p=PRODUCT_CATALOG[g.catalogKey],vars=variantsForGroupV3(g,w),total=rowsForGroupV3(g,w,true).reduce((a,r)=>a+availableStock(r),0);return `<div class="product-group"><div class="product-group-head"><div><span class="group-number">${i+1}</span><b>Producto ${i+1}</b><div class="muted">${w?`${esc(w)} · ${total} unidades disponibles`:'Selecciona bodega'}</div></div><div class="group-actions"><button class="btn light sm" onclick="regenerateGroupV3('${g.id}')">↻ Nuevo surtido</button>${currentGroups.length>1?`<button class="btn danger-lite sm" onclick="removeProductGroupV3('${g.id}')">Quitar</button>`:''}</div></div><div class="group-config"><div class="field"><label>Tipo de producto</label><select onchange="updateGroupV3('${g.id}','catalogKey',this.value)">${Object.entries(PRODUCT_CATALOG).map(([k,x])=>`<option value="${k}" ${k===g.catalogKey?'selected':''}>${x.label}</option>`).join('')}</select></div><div class="field"><label>Cantidad</label><select onchange="updateGroupV3('${g.id}','qty',this.value)">${p.quantities.map(q=>`<option ${Number(g.qty)===q?'selected':''}>${q}</option>`).join('')}</select></div><div class="field"><label>Talla</label><select onchange="updateGroupV3('${g.id}','size',this.value)">${p.sizes.map(s=>`<option ${g.size===s?'selected':''}>${s}</option>`).join('')}</select></div></div><div class="unit-head"><span>#</span><span>Diseño / color</span><span>Talla</span><span>Disponible</span><span>Estado</span></div><div class="units">${g.units.map((u,n)=>unitHtmlV3(g,u,n,w,vars)).join('')}</div></div>`}
function unitHtmlV3(g,u,i,w,vars){const r=w&&u.variantKey?recordV3(u.variantKey,w):null,a=r?availableStock(r):(vars.find(v=>v.variantKey===u.variantKey)?.available||0),st=!u.variantKey?'Sin definir':w&&!r?'No existe aquí':a<=0?'Agotado':a<=5?'Crítico':'OK',cls=st==='OK'?'green':st==='Crítico'?'amber':'red',label=u.design?((g.catalogKey==='adulto_estampado'||g.catalogKey==='ninos_estampado')?`Diseño #${u.design}`:u.design):'Seleccionar';return `<div class="unit unit-v3"><span class="n">${i+1}</span><select onchange="changeUnitV3('${g.id}',${i},this.value)"><option value="${esc(u.variantKey||'')}">${esc(label)}${u.variantKey?` · ${a} disp.`:''}</option>${vars.filter(v=>v.variantKey!==u.variantKey).map(v=>`<option value="${esc(v.variantKey)}">${esc((g.catalogKey==='adulto_estampado'||g.catalogKey==='ninos_estampado')?`Diseño #${v.design}`:v.design)} · ${v.available} disp.</option>`).join('')}</select><span><b>${esc(g.size)}</b></span><span class="${a<=3?'stock-low':'stock-ok'}">${u.variantKey?a:'—'}</span><span class="tag ${cls}">${st}</span></div>`}
function warehouseChangedV3(){renderProductGroupsV3();updateRecommendationV3();checkBlockingV3()}
function updateRecommendationV3(){if(!el('warehouseRec'))return;const rec=chooseWarehouseV3(true),w=el('fWarehouse').value;if(!w&&rec&&state.inventory.length){el('fWarehouse').value=rec;currentGroups.forEach(g=>ensureGroupUnitsV3(g,true,rec));renderProductGroupsV3()}if(!state.inventory.length)el('warehouseRec').innerHTML='<b>Stock pendiente:</b> carga inventario para validar el pedido.';else if(rec&&canExactFulfillV3(rec))el('warehouseRec').innerHTML=`<b>Recomendación:</b> ${esc(rec)} puede despachar todas las unidades exactas.`;else if(rec&&canAutoFulfillV3(rec))el('warehouseRec').innerHTML=`<b>Recomendación:</b> ${esc(rec)} tiene suficiente stock total. Regenera/cambia las referencias que no coincidan.`;else el('warehouseRec').innerHTML='<b>Atención:</b> ninguna bodega cubre el pedido completo. Ajusta referencias con el cliente antes de dividir el envío.';renderProductGroupsV3()}
function stockProblemsV3(w){const a=[];currentGroups.forEach((g,i)=>{if(g.units.length!==Number(g.qty)||g.units.some(u=>!u.variantKey))a.push(`Producto ${i+1}: faltan unidades por definir.`)});for(const [vk,n] of exactCountsV3()){const r=recordV3(vk,w),have=r?availableStock(r):0;if(have<n){const any=state.inventory.find(x=>x.variantKey===vk);a.push(`${any?designDisplay(any):'Referencia'}: requiere ${n}, disponibles ${have}.`)}}return a}
function checkBlockingV3(){if(!el('blockAlert'))return false;const a=[];if(!el('fName').value.trim()||!el('fPhone').value.trim()||!el('fCity').value.trim()||!el('fAddress').value.trim())a.push('Faltan datos obligatorios del cliente.');if(!Number(el('fPrice').value))a.push('El valor total es obligatorio.');const w=el('fWarehouse').value;if(!w)a.push('Selecciona una bodega.');if(!state.inventory.length)a.push('No hay inventario cargado.');if(w&&state.inventory.length)a.push(...stockProblemsV3(w).slice(0,5));const b=el('blockAlert'),badge=el('blockBadge');if(a.length){b.innerHTML='<b>Alerta roja · debes resolver:</b><br>'+a.map(x=>'• '+esc(x)).join('<br>');b.classList.remove('hidden');badge.classList.remove('hidden');return true}b.classList.add('hidden');badge.classList.add('hidden');return false}
function exactItemsV3(w){const out=[];currentGroups.forEach((g,gi)=>g.units.forEach((u,ui)=>{const r=recordV3(u.variantKey,w);out.push({...u,groupId:g.id,groupIndex:gi+1,unitIndex:ui+1,inventoryId:r?.id||'',warehouse:w,externalId:r?.externalId||''})}));return out}
function reserveItemsV3(items,w){const c=new Map();items.forEach(x=>c.set(x.variantKey,(c.get(x.variantKey)||0)+1));for(const [vk,n] of c){const r=recordV3(vk,w);if(r)r.reserved=Number(r.reserved||0)+n}}
function summaryV3(){return currentGroups.map(g=>`${g.qty} ${PRODUCT_CATALOG[g.catalogKey].label} · ${g.size}`).join(' + ')}
function saveOrderV3(confirm){if(confirm&&checkBlockingV3())return toast('Resuelve la alerta roja antes de confirmar');const w=el('fWarehouse').value,groups=currentGroups.map(g=>({...g,units:g.units.map(u=>({...u}))})),items=exactItemsV3(w),qty=groups.reduce((a,g)=>a+Number(g.qty),0),data={name:el('fName').value.trim(),phone:el('fPhone').value.trim(),city:el('fCity').value.trim(),department:el('fDepartment').value.trim(),address:el('fAddress').value.trim(),source:el('fSource').value,advisor:el('fAdvisor').value,status:confirm?'Confirmada':el('fStatus').value,attempts:Number(el('fAttempts').value||0),qty,price:Number(el('fPrice').value),size:groups.length===1?groups[0].size:'MIXTO',summary:summaryV3(),warehouse:w,carrier:el('fCarrier').value,groups,items,payment:el('fPayment').value,deliveryMode:el('fDeliveryMode').value,notes:el('fNotes').value};if(editingSaleId){const s=state.sales.find(x=>x.id===editingSaleId);if(confirm&&s.status!=='Confirmada')reserveItemsV3(items,w);Object.assign(s,data,{confirmedAt:confirm?new Date().toISOString():s.confirmedAt})}else{const id='V-'+String(state.sales.length+1).padStart(3,'0');if(confirm)reserveItemsV3(items,w);state.sales.unshift({id,createdAt:new Date().toISOString(),cutId:null,...data,confirmedAt:confirm?new Date().toISOString():null})}saveState();closeOrder();switchView('sales');renderAI();toast(confirm?'Venta confirmada y stock reservado':'Gestión guardada')}
