const langBtns=[...document.querySelectorAll('[data-lang]')];
function setLang(lang){document.documentElement.lang=lang;langBtns.forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.querySelectorAll('[data-es][data-en]').forEach(el=>{el.textContent=el.dataset[lang]});renderXray();}
langBtns.forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));

const XRAY={
 es:{
  'VENTAS':{items:['Muchos prospectos, pocos cierres','Seguimiento inconsistente','CRM usado solo como base de datos','Dependencia de vendedores específicos','Poca visibilidad sobre por qué se pierden oportunidades'],hyp:'El problema puede no ser conseguir más leads.',copy:'La fuga puede estar en el proceso comercial, el seguimiento o la forma en la que las oportunidades avanzan entre etapas.'},
  'MARKETING':{items:['Campañas sin conexión con ventas','Mensajes que atraen pero no califican','Canales evaluados por métricas aisladas','Poca retroalimentación desde el equipo comercial','Demasiada dependencia de pauta'],hyp:'Generar demanda no garantiza crecimiento.',copy:'Marketing necesita operar conectado con el proceso comercial, la capacidad operativa y la rentabilidad real de cada canal.'},
  'OPERACIONES':{items:['Procesos manuales','Tareas duplicadas','Información repartida','Crecimiento = más caos','Responsabilidades poco claras'],hyp:'La operación puede estar absorbiendo el crecimiento.',copy:'Si cada nueva venta agrega fricción en lugar de eficiencia, el problema está en la arquitectura operativa.'},
  'RENTABILIDAD':{items:['Facturación sube y utilidad no','Costos que nadie cuestiona','Descuentos usados para cerrar','Procesos costosos','Recursos mal asignados'],hyp:'Facturar más no siempre significa ganar más.',copy:'La rentabilidad se puede perder entre adquisición, descuentos, operación, retrabajo y decisiones sin visibilidad.'},
  'E-COMMERCE':{items:['Conversión inestable','Fricción en checkout','Poca retención','Datos aislados','Postventa sin sistema'],hyp:'La tienda puede estar vendiendo por debajo de su capacidad.',copy:'Conversión, adquisición, experiencia y retención deben funcionar como un mismo sistema.'},
  'EQUIPO':{items:['Decisiones centralizadas','Roles ambiguos','Reuniones sin ejecución','Dependencia del dueño','Falta de accountability'],hyp:'El equipo puede necesitar estructura, no más personas.',copy:'Contratar sin redefinir responsabilidades suele agregar complejidad en vez de capacidad.'},
  'PROCESOS':{items:['Retrabajo','Aprobaciones innecesarias','Falta de estándares','Duplicación de información','Errores repetitivos'],hyp:'La empresa puede estar pagando por su propia fricción.',copy:'Los procesos deben reducir esfuerzo y variabilidad, no convertir cada tarea en una excepción.'},
  'AUTOMATIZACIÓN':{items:['Trabajo repetitivo','Herramientas desconectadas','Copiar y pegar información','Seguimientos manuales','Poca trazabilidad'],hyp:'Automatizar sí, pero después de ordenar.',copy:'Automatizar un proceso roto solo acelera el problema. Primero se diseña, después se automatiza.'},
  'IA':{items:['IA usada sin objetivo','Bots sin integración','Datos sin aprovechar','Tareas cognitivas repetitivas','Equipos sin workflows de IA'],hyp:'La IA debe ser una capa del negocio.',copy:'Su valor aparece cuando se integra a procesos claros y mejora productividad, velocidad, experiencia o rentabilidad.'}
 },
 en:{
  'SALES':{items:['Many prospects, few closes','Inconsistent follow-up','CRM used only as a database','Dependency on specific sellers','Low visibility into lost opportunities'],hyp:'The problem may not be getting more leads.',copy:'The leak may be in the sales process, follow-up or the way opportunities move between stages.'},
  'MARKETING':{items:['Campaigns disconnected from sales','Messages that attract but do not qualify','Channels judged by isolated metrics','Little feedback from sales','Too much paid-media dependency'],hyp:'Demand generation does not guarantee growth.',copy:'Marketing must operate connected to sales, operational capacity and real channel profitability.'},
  'OPERATIONS':{items:['Manual processes','Duplicated tasks','Scattered information','Growth creates more chaos','Unclear ownership'],hyp:'Operations may be absorbing the growth.',copy:'If every new sale creates friction instead of efficiency, the issue is operational architecture.'},
  'PROFITABILITY':{items:['Revenue rises but profit does not','Unquestioned costs','Discounts used to close','Expensive processes','Poor resource allocation'],hyp:'More revenue does not always mean more profit.',copy:'Profitability can leak across acquisition, discounts, operations, rework and low-visibility decisions.'},
  'E-COMMERCE':{items:['Unstable conversion','Checkout friction','Low retention','Isolated data','No post-sale system'],hyp:'The store may be selling below its capacity.',copy:'Conversion, acquisition, experience and retention must work as one system.'},
  'TEAM':{items:['Centralized decisions','Ambiguous roles','Meetings without execution','Owner dependency','Low accountability'],hyp:'The team may need structure, not more people.',copy:'Hiring without redefining ownership often adds complexity instead of capacity.'},
  'PROCESSES':{items:['Rework','Unnecessary approvals','No standards','Duplicate information','Repeated errors'],hyp:'The company may be paying for its own friction.',copy:'Processes should reduce effort and variability, not turn every task into an exception.'},
  'AUTOMATION':{items:['Repetitive work','Disconnected tools','Copy-paste workflows','Manual follow-up','Low traceability'],hyp:'Automate, but only after organizing.',copy:'Automating a broken process only accelerates the problem. Design first, automate second.'},
  'AI':{items:['AI without a clear goal','Bots without integration','Unused data','Repetitive cognitive tasks','Teams without AI workflows'],hyp:'AI should be a layer of the business.',copy:'Its value appears when integrated into clear processes and improves productivity, speed, experience or profitability.'}
 }
};
let xrayKey='VENTAS';
function renderXray(){const lang=document.documentElement.lang||'es';const data=XRAY[lang];const keys=Object.keys(data);if(!data[xrayKey]) xrayKey=keys[0];const tabs=document.getElementById('xrayTabs');tabs.innerHTML='';keys.forEach(k=>{const b=document.createElement('button');b.className='xray-tab'+(k===xrayKey?' active':'');b.textContent=k;b.onclick=()=>{xrayKey=k;renderXray()};tabs.appendChild(b)});const d=data[xrayKey];document.getElementById('diagTitle').textContent=xrayKey;document.getElementById('diagList').innerHTML=d.items.map(i=>`<li>${i}</li>`).join('');document.getElementById('diagHypothesis').textContent=d.hyp;document.getElementById('diagCopy').textContent=d.copy;}
renderXray();

const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));

const nodes=[...document.querySelectorAll('.engine-node')],status=document.getElementById('engineStatus');let phase=0;const phases=['Friction detected','Diagnosis running','Restructuring','System aligned · Ready to scale'];setInterval(()=>{nodes.forEach(n=>n.classList.remove('active'));nodes[phase%nodes.length].classList.add('active');status.textContent=phases[Math.floor(phase/2)%phases.length];phase=(phase+1)%12},1200);

if(matchMedia('(pointer:fine)').matches){document.addEventListener('mousemove',e=>{document.documentElement.style.setProperty('--mx',(e.clientX/innerWidth*100)+'%');document.documentElement.style.setProperty('--my',(e.clientY/innerHeight*100)+'%')})}

document.getElementById('qualifyForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const lang=document.documentElement.lang||'es';const msg=lang==='es'?`Hola Samuel. Quiero solicitar un diagnóstico estratégico.%0A%0ANombre: ${encodeURIComponent(f.get('name'))}%0AEmpresa: ${encodeURIComponent(f.get('company'))}%0AFreno: ${encodeURIComponent(f.get('bottleneck'))}%0AFacturación: ${encodeURIComponent(f.get('revenue'))}%0AObjetivo: ${encodeURIComponent(f.get('goal'))}`:`Hi Samuel. I want to request a strategic diagnosis.%0A%0AName: ${encodeURIComponent(f.get('name'))}%0ACompany: ${encodeURIComponent(f.get('company'))}%0ABottleneck: ${encodeURIComponent(f.get('bottleneck'))}%0ARevenue: ${encodeURIComponent(f.get('revenue'))}%0AGoal: ${encodeURIComponent(f.get('goal'))}`;document.getElementById('waLink').href='https://wa.me/573028289997?text='+msg;document.getElementById('nextOptions').classList.add('show');document.getElementById('nextOptions').scrollIntoView({behavior:'smooth',block:'nearest'})});